In [210]:
import random as rd
import numpy as np

In [259]:
class xor():
    def __init__(self,n): 
        # n is the number of neurons in the hidden layer
        self.layers_Z={1:[] , 2:[]}
        self.layers_A={0:[], 1:[] , 2:[]}
        self.weights={1:[[rd.uniform(0.0, 1.0) for i in range(2)] for j in range(n)], 
                     2:[rd.uniform(0.0, 1.0) for i in range(n)]}
        self.b= {1: [[0],[0]] , 2:[0]}
        self.activation= "relu"
        self.loss=[]  # plot this loss afterwards
        
    def affineForward(self,x, w, b):
        return np.dot(self.weights[w],x) + self.b[b]

    
    def activationForward(self, A):


        if self.activation == "sig":
            A = self.sigmoid(A)
        elif self.activation == "relu":
            A = self.relu(A)
        return A
    
    def sigmoid(self, X):
        x = X.copy()
        out = 1/(1 + np.exp(-x))
        return out
    
    def relu(self, X):
        activation = np.maximum(0,X)
        return activation
    
    def lossfunction(self, y_hat, y ):
        print("print")
        print(y_hat)
        print(y)
        print sum((y_hat-y)**2)
        loss = 1.0/2*float(sum((y_hat-y)**2))

        
        dAL = y_hat - y
        return loss, dAL
            
        
    
    def forward_prop(self,data):
#         inp= [[0, 1],[1,1]]
#         out=out
        self.layers_A[0]= data
        self.layers_Z[1]= self.affineForward(self.layers_A[0],1,1)
        self.layers_A[1]= self.activationForward(self.layers_Z[1])
        self.layers_Z[2]= self.affineForward(self.layers_A[1],2,2)
        self.layers_A[2]=self.activationForward(self.layers_Z[2])
        return self.layers_A[2]
    
    def background_prop(self, target, alpha):
        loss, dA_2= self.lossfunction(self.layers_A[2],target)
        self.loss.append(loss)
        print(" loss is "+ str(loss))
        gZ_2= self.G_Z(self.layers_Z[2])
        dZ_2= dA_2 * gZ_2

        dA_1= np.dot(np.matrix(self.weights[2]).T, np.matrix(dZ_2))
        
        dW_2= np.dot(np.matrix(dZ_2), np.matrix(self.layers_A[1]).T)
        dW_2= np.array(dW_2)[0]

        gZ_1= self.G_Z(self.layers_Z[1],)
        
        dZ_1= np.array(dA_1) * np.array(gZ_1)
        
        dA_0= np.dot(np.matrix(self.weights[1]).T, np.matrix(dZ_1))
        
        
        dW_1= np.dot(np.matrix(dZ_1), np.matrix(self.layers_A[0]).T)
        dW_1= np.array(dW_1)

        
#         print(alpha * dW_2)
#         print(alpha * dW_1)
        # update weights
        self.weights[2] = self.weights[2] - alpha * dW_2
        self.weights[1] = self.weights[1] - alpha * dW_1
        
        return 1
        
    def G_Z(self, Z):
        x = Z.copy()
        if self.activation == "sig":
            out = np.exp(-x)/((1 + np.exp(-x))**2)
        elif self.activation == "relu":
            out = x * 1 * (x > 0)
        return out        
        
        
        return out
    
    
    def train(self, data, out,alpha):
        for i in range(10000):
            print("pass "+ str(i))
            
            self.forward_prop(data)       
            self.background_prop(out, alpha)
            


In [260]:
out=[0,1,1,0]
inp= [[0,0,1,1],[0,1,0,1]]

In [278]:
out=[0,1,1,0]
inp= [[0,1,0,1],[0,0,1,1]]
nn= xor(2)
# nn.forward_prop(inp, out)
nn.train(inp,out,.1)

pass 0
print
[0.        0.6720073 0.3374783 1.0094856]
[0, 1, 1, 0]
1.5655753877189489
 loss is 0.782787693859
pass 1
print
[0.         0.51068666 0.23292578 0.74361245]
[0, 1, 1, 0]
1.3807898665562441
 loss is 0.690394933278
pass 2
print
[0.         0.45585211 0.19716915 0.65302126]
[0, 1, 1, 0]
1.3670710652432012
 loss is 0.683535532622
pass 3
print
[0.         0.42340437 0.17549052 0.59889489]
[0, 1, 1, 0]
1.3709534919277115
 loss is 0.685476745964
pass 4
print
[0.         0.40152303 0.16033274 0.56185578]
[0, 1, 1, 0]
1.3788976953287102
 loss is 0.689448847664
pass 5
print
[0.         0.38577703 0.14889869 0.53467572]
[0, 1, 1, 0]
1.3875214222552967
 loss is 0.693760711128
pass 6
print
[0.         0.37400878 0.13984013 0.51384891]
[0, 1, 1, 0]
1.3957807145870331
 loss is 0.697890357294
pass 7
print
[0.         0.36500727 0.13240653 0.4974138 ]
[0, 1, 1, 0]
1.4033546860621176
 loss is 0.701677343031
pass 8
print
[0.         0.35802747 0.12613922 0.48416668]
[0, 1, 1, 0]
1.4101787792

pass 264
print
[0.         0.99617599 0.         0.08583609]
[0, 1, 1, 0]
1.007382456887631
 loss is 0.503691228444
pass 265
print
[0.         0.99622717 0.         0.08527578]
[0, 1, 1, 0]
1.0072861933292898
 loss is 0.503643096665
pass 266
print
[0.         0.99627739 0.         0.08472204]
[0, 1, 1, 0]
1.0071916824575793
 loss is 0.503595841229
pass 267
print
[0.         0.99632667 0.         0.08417476]
[0, 1, 1, 0]
1.007098884173518
 loss is 0.503549442087
pass 268
print
[0.         0.99637503 0.         0.08363384]
[0, 1, 1, 0]
1.0070077594652613
 loss is 0.503503879733
pass 269
print
[0.         0.99642251 0.         0.08309917]
[0, 1, 1, 0]
1.0069182703744952
 loss is 0.503459135187
pass 270
print
[0.         0.9964691  0.         0.08257065]
[0, 1, 1, 0]
1.006830379963983
 loss is 0.503415189982
pass 271
print
[0.         0.99651485 0.         0.08204819]
[0, 1, 1, 0]
1.006744052286219
 loss is 0.503372026143
pass 272
print
[0.         0.99655976 0.         0.08153169]
[0, 1, 

[0, 1, 1, 0]
1.0009078698026095
 loss is 0.500453934901
pass 524
print
[0.         0.99954669 0.         0.0300489 ]
[0, 1, 1, 0]
1.0009031421520722
 loss is 0.500451571076
pass 525
print
[0.         0.99954907 0.         0.02997077]
[0, 1, 1, 0]
1.0008984505251308
 loss is 0.500449225263
pass 526
print
[0.         0.99955142 0.         0.02989303]
[0, 1, 1, 0]
1.0008937945629217
 loss is 0.500446897281
pass 527
print
[0.         0.99955376 0.         0.02981568]
[0, 1, 1, 0]
1.0008891739109758
 loss is 0.500444586955
pass 528
print
[0.         0.99955608 0.         0.02973871]
[0, 1, 1, 0]
1.000884588219155
 loss is 0.50044229411
pass 529
print
[0.         0.99955838 0.         0.02966213]
[0, 1, 1, 0]
1.0008800371415911
 loss is 0.500440018571
pass 530
print
[0.         0.99956066 0.         0.02958593]
[0, 1, 1, 0]
1.0008755203366217
 loss is 0.500437760168
pass 531
print
[0.         0.99956293 0.         0.02951011]
[0, 1, 1, 0]
1.0008710374667318
 loss is 0.500435518733
pass 532
p

1.000314696876605
 loss is 0.500157348438
pass 787
print
[0.         0.99984353 0.         0.017711  ]
[0, 1, 1, 0]
1.000313703875295
 loss is 0.500156851938
pass 788
print
[0.         0.99984402 0.         0.01768308]
[0, 1, 1, 0]
1.0003127155060068
 loss is 0.500156357753
pass 789
print
[0.         0.99984452 0.         0.01765524]
[0, 1, 1, 0]
1.00031173174026
 loss is 0.50015586587
pass 790
print
[0.         0.99984501 0.         0.01762749]
[0, 1, 1, 0]
1.0003107525497903
 loss is 0.500155376275
pass 791
print
[0.         0.99984549 0.         0.01759983]
[0, 1, 1, 0]
1.0003097779065482
 loss is 0.500154888953
pass 792
print
[0.         0.99984598 0.         0.01757225]
[0, 1, 1, 0]
1.0003088077826976
 loss is 0.500154403891
pass 793
print
[0.         0.99984646 0.         0.01754476]
[0, 1, 1, 0]
1.000307842150613
 loss is 0.500153921075
pass 794
print
[0.         0.99984695 0.         0.01751735]
[0, 1, 1, 0]
1.0003068809828786
 loss is 0.500153440491
pass 795
print
[0.         

pass 1061
print
[0.         0.99992427 0.         0.012338  ]
[0, 1, 1, 0]
1.0001522320477334
 loss is 0.500076116024
pass 1062
print
[0.         0.99992444 0.         0.01232429]
[0, 1, 1, 0]
1.0001518937372433
 loss is 0.500075946869
pass 1063
print
[0.         0.99992461 0.         0.0123106 ]
[0, 1, 1, 0]
1.0001515565431511
 loss is 0.500075778272
pass 1064
print
[0.         0.99992478 0.         0.01229694]
[0, 1, 1, 0]
1.0001512204605836
 loss is 0.50007561023
pass 1065
print
[0.         0.99992494 0.         0.01228332]
[0, 1, 1, 0]
1.0001508854846937
 loss is 0.500075442742
pass 1066
print
[0.         0.99992511 0.         0.01226972]
[0, 1, 1, 0]
1.0001505516106615
 loss is 0.500075275805
pass 1067
print
[0.         0.99992527 0.         0.01225615]
[0, 1, 1, 0]
1.000150218833692
 loss is 0.500075109417
pass 1068
print
[0.         0.99992544 0.         0.01224261]
[0, 1, 1, 0]
1.0001498871490169
 loss is 0.500074943575
pass 1069
print
[0.         0.99992561 0.         0.012229

pass 1311
print
[0.         0.99995378 0.         0.00964561]
[0, 1, 1, 0]
1.0000930400072474
 loss is 0.500046520004
pass 1312
print
[0.         0.99995386 0.         0.00963718]
[0, 1, 1, 0]
1.0000928773497029
 loss is 0.500046438675
pass 1313
print
[0.         0.99995394 0.         0.00962876]
[0, 1, 1, 0]
1.0000927151153471
 loss is 0.500046357558
pass 1314
print
[0.         0.99995402 0.         0.00962035]
[0, 1, 1, 0]
1.0000925533027212
 loss is 0.500046276651
pass 1315
print
[0.         0.9999541  0.         0.00961196]
[0, 1, 1, 0]
1.000092391910372
 loss is 0.500046195955
pass 1316
print
[0.         0.99995418 0.         0.00960358]
[0, 1, 1, 0]
1.0000922309368532
 loss is 0.500046115468
pass 1317
print
[0.         0.99995426 0.         0.00959522]
[0, 1, 1, 0]
1.0000920703807246
 loss is 0.50004603519
pass 1318
print
[0.         0.99995434 0.         0.00958687]
[0, 1, 1, 0]
1.000091910240552
 loss is 0.50004595512
pass 1319
print
[0.         0.99995442 0.         0.00957854

 loss is 0.500031338157
pass 1561
print
[0.         0.99996893 0.         0.00791107]
[0, 1, 1, 0]
1.00006258601861
 loss is 0.500031293009
pass 1562
print
[0.         0.99996898 0.         0.00790538]
[0, 1, 1, 0]
1.0000624959168656
 loss is 0.500031247958
pass 1563
print
[0.         0.99996902 0.         0.00789969]
[0, 1, 1, 0]
1.000062406008435
 loss is 0.500031203004
pass 1564
print
[0.         0.99996907 0.         0.00789401]
[0, 1, 1, 0]
1.0000623162927684
 loss is 0.500031158146
pass 1565
print
[0.         0.99996911 0.         0.00788833]
[0, 1, 1, 0]
1.0000622267693169
 loss is 0.500031113385
pass 1566
print
[0.         0.99996916 0.         0.00788267]
[0, 1, 1, 0]
1.0000621374375347
 loss is 0.500031068719
pass 1567
print
[0.         0.9999692  0.         0.00787701]
[0, 1, 1, 0]
1.000062048296877
 loss is 0.500031024148
pass 1568
print
[0.         0.99996925 0.         0.00787137]
[0, 1, 1, 0]
1.0000619593468016
 loss is 0.500030979673
pass 1569
print
[0.         0.999969

 loss is 0.500022105684
pass 1825
print
[0.         0.99997809 0.         0.00664509]
[0, 1, 1, 0]
1.0000441577163286
 loss is 0.500022078858
pass 1826
print
[0.         0.99997812 0.         0.00664106]
[0, 1, 1, 0]
1.0000441041610313
 loss is 0.500022052081
pass 1827
print
[0.         0.99997815 0.         0.00663703]
[0, 1, 1, 0]
1.0000440507026336
 loss is 0.500022025351
pass 1828
print
[0.         0.99997817 0.         0.00663301]
[0, 1, 1, 0]
1.0000439973409034
 loss is 0.50002199867
pass 1829
print
[0.        0.9999782 0.        0.006629 ]
[0, 1, 1, 0]
1.0000439440756081
 loss is 0.500021972038
pass 1830
print
[0.         0.99997823 0.         0.00662499]
[0, 1, 1, 0]
1.0000438909065166
 loss is 0.500021945453
pass 1831
print
[0.         0.99997825 0.         0.00662098]
[0, 1, 1, 0]
1.000043837833398
 loss is 0.500021918917
pass 1832
print
[0.         0.99997828 0.         0.00661698]
[0, 1, 1, 0]
1.0000437848560224
 loss is 0.500021892428
pass 1833
print
[0.         0.99997831

pass 2084
print
[0.         0.99998365 0.         0.00574158]
[0, 1, 1, 0]
1.000032965966361
 loss is 0.500016482983
pass 2085
print
[0.         0.99998367 0.         0.00573856]
[0, 1, 1, 0]
1.0000329313484129
 loss is 0.500016465674
pass 2086
print
[0.         0.99998369 0.         0.00573555]
[0, 1, 1, 0]
1.0000328967847378
 loss is 0.500016448392
pass 2087
print
[0.         0.99998371 0.         0.00573254]
[0, 1, 1, 0]
1.000032862275223
 loss is 0.500016431138
pass 2088
print
[0.         0.99998372 0.         0.00572953]
[0, 1, 1, 0]
1.0000328278197552
 loss is 0.50001641391
pass 2089
print
[0.         0.99998374 0.         0.00572653]
[0, 1, 1, 0]
1.0000327934182223
 loss is 0.500016396709
pass 2090
print
[0.         0.99998376 0.         0.00572353]
[0, 1, 1, 0]
1.0000327590705123
 loss is 0.500016379535
pass 2091
print
[0.         0.99998377 0.         0.00572053]
[0, 1, 1, 0]
1.0000327247765126
 loss is 0.500016362388
pass 2092
print
[0.         0.99998379 0.         0.0057175

1.0000249776359158
 loss is 0.500012488818
pass 2368
print
[0.         0.99998763 0.         0.00499546]
[0, 1, 1, 0]
1.000024954765252
 loss is 0.500012477383
pass 2369
print
[0.         0.99998764 0.         0.00499317]
[0, 1, 1, 0]
1.0000249319258723
 loss is 0.500012465963
pass 2370
print
[0.         0.99998765 0.         0.00499089]
[0, 1, 1, 0]
1.000024909117719
 loss is 0.500012454559
pass 2371
print
[0.         0.99998766 0.         0.00498861]
[0, 1, 1, 0]
1.0000248863407362
 loss is 0.50001244317
pass 2372
print
[0.         0.99998768 0.         0.00498633]
[0, 1, 1, 0]
1.0000248635948665
 loss is 0.500012431797
pass 2373
print
[0.         0.99998769 0.         0.00498405]
[0, 1, 1, 0]
1.000024840880054
 loss is 0.50001242044
pass 2374
print
[0.         0.9999877  0.         0.00498177]
[0, 1, 1, 0]
1.0000248181962423
 loss is 0.500012409098
pass 2375
print
[0.         0.99998771 0.         0.0049795 ]
[0, 1, 1, 0]
1.0000247955433748
 loss is 0.500012397772
pass 2376
print
[0

[0, 1, 1, 0]
1.0000194594805683
 loss is 0.50000972974
pass 2658
print
[0.         0.99999036 0.         0.00440949]
[0, 1, 1, 0]
1.0000194437320655
 loss is 0.500009721866
pass 2659
print
[0.         0.99999037 0.         0.00440771]
[0, 1, 1, 0]
1.0000194280026116
 loss is 0.500009714001
pass 2660
print
[0.         0.99999038 0.         0.00440593]
[0, 1, 1, 0]
1.0000194122921757
 loss is 0.500009706146
pass 2661
print
[0.         0.99999039 0.         0.00440415]
[0, 1, 1, 0]
1.0000193966007276
 loss is 0.5000096983
pass 2662
print
[0.         0.9999904  0.         0.00440237]
[0, 1, 1, 0]
1.0000193809282365
 loss is 0.500009690464
pass 2663
print
[0.         0.9999904  0.         0.00440059]
[0, 1, 1, 0]
1.0000193652746723
 loss is 0.500009682637
pass 2664
print
[0.         0.99999041 0.         0.00439881]
[0, 1, 1, 0]
1.0000193496400043
 loss is 0.50000967482
pass 2665
print
[0.         0.99999042 0.         0.00439704]
[0, 1, 1, 0]
1.000019334024202
 loss is 0.500009667012
pass 

[0, 1, 1, 0]
1.0000158810959576
 loss is 0.500007940548
pass 2922
print
[0.         0.99999214 0.         0.00398364]
[0, 1, 1, 0]
1.000015869473652
 loss is 0.500007934737
pass 2923
print
[0.         0.99999214 0.         0.00398219]
[0, 1, 1, 0]
1.000015857864063
 loss is 0.500007928932
pass 2924
print
[0.         0.99999215 0.         0.00398073]
[0, 1, 1, 0]
1.0000158462671722
 loss is 0.500007923134
pass 2925
print
[0.         0.99999215 0.         0.00397927]
[0, 1, 1, 0]
1.0000158346829613
 loss is 0.500007917341
pass 2926
print
[0.         0.99999216 0.         0.00397782]
[0, 1, 1, 0]
1.0000158231114118
 loss is 0.500007911556
pass 2927
print
[0.         0.99999217 0.         0.00397637]
[0, 1, 1, 0]
1.000015811552505
 loss is 0.500007905776
pass 2928
print
[0.         0.99999217 0.         0.00397491]
[0, 1, 1, 0]
1.0000158000062231
 loss is 0.500007900003
pass 2929
print
[0.         0.99999218 0.         0.00397346]
[0, 1, 1, 0]
1.0000157884725474
 loss is 0.500007894236
pas

print
[0.         0.99999327 0.         0.00368546]
[0, 1, 1, 0]
1.0000135826306376
 loss is 0.500006791315
pass 3144
print
[0.         0.99999328 0.         0.00368421]
[0, 1, 1, 0]
1.0000135734314564
 loss is 0.500006786716
pass 3145
print
[0.         0.99999328 0.         0.00368296]
[0, 1, 1, 0]
1.0000135642415924
 loss is 0.500006782121
pass 3146
print
[0.         0.99999329 0.         0.00368171]
[0, 1, 1, 0]
1.0000135550610332
 loss is 0.500006777531
pass 3147
print
[0.         0.99999329 0.         0.00368047]
[0, 1, 1, 0]
1.0000135458897668
 loss is 0.500006772945
pass 3148
print
[0.         0.99999329 0.         0.00367922]
[0, 1, 1, 0]
1.0000135367277796
 loss is 0.500006768364
pass 3149
print
[0.         0.9999933  0.         0.00367798]
[0, 1, 1, 0]
1.00001352757506
 loss is 0.500006763788
pass 3150
print
[0.         0.9999933  0.         0.00367674]
[0, 1, 1, 0]
1.0000135184315952
 loss is 0.500006759216
pass 3151
print
[0.         0.99999331 0.         0.00367549]
[0, 1,

1.0000115435889403
 loss is 0.500005771794
pass 3394
print
[0.         0.99999429 0.         0.00339652]
[0, 1, 1, 0]
1.0000115363766282
 loss is 0.500005768188
pass 3395
print
[0.         0.99999429 0.         0.00339546]
[0, 1, 1, 0]
1.0000115291710565
 loss is 0.500005764586
pass 3396
print
[0.         0.99999429 0.         0.0033944 ]
[0, 1, 1, 0]
1.0000115219722172
 loss is 0.500005760986
pass 3397
print
[0.         0.9999943  0.         0.00339334]
[0, 1, 1, 0]
1.0000115147801016
 loss is 0.50000575739
pass 3398
print
[0.         0.9999943  0.         0.00339228]
[0, 1, 1, 0]
1.0000115075947011
 loss is 0.500005753797
pass 3399
print
[0.         0.9999943  0.         0.00339122]
[0, 1, 1, 0]
1.0000115004160077
 loss is 0.500005750208
pass 3400
print
[0.         0.99999431 0.         0.00339016]
[0, 1, 1, 0]
1.0000114932440132
 loss is 0.500005746622
pass 3401
print
[0.         0.99999431 0.         0.00338911]
[0, 1, 1, 0]
1.000011486078709
 loss is 0.500005743039
pass 3402
print

[0, 1, 1, 0]
1.000009930635907
 loss is 0.500004965318
pass 3644
print
[0.         0.99999508 0.         0.00315037]
[0, 1, 1, 0]
1.0000099248778382
 loss is 0.500004962439
pass 3645
print
[0.         0.99999509 0.         0.00314946]
[0, 1, 1, 0]
1.0000099191247651
 loss is 0.500004959562
pass 3646
print
[0.         0.99999509 0.         0.00314855]
[0, 1, 1, 0]
1.000009913376681
 loss is 0.500004956688
pass 3647
print
[0.         0.99999509 0.         0.00314764]
[0, 1, 1, 0]
1.0000099076335807
 loss is 0.500004953817
pass 3648
print
[0.         0.9999951  0.         0.00314672]
[0, 1, 1, 0]
1.0000099018954585
 loss is 0.500004950948
pass 3649
print
[0.         0.9999951  0.         0.00314581]
[0, 1, 1, 0]
1.0000098961623078
 loss is 0.500004948081
pass 3650
print
[0.        0.9999951 0.        0.0031449]
[0, 1, 1, 0]
1.000009890434124
 loss is 0.500004945217
pass 3651
print
[0.         0.9999951  0.         0.00314399]
[0, 1, 1, 0]
1.0000098847109007
 loss is 0.500004942355
pass 36

print
[0.         0.99999583 0.         0.00290052]
[0, 1, 1, 0]
1.0000084130319806
 loss is 0.500004206516
pass 3942
print
[0.         0.99999584 0.         0.00289975]
[0, 1, 1, 0]
1.0000084085394347
 loss is 0.50000420427
pass 3943
print
[0.         0.99999584 0.         0.00289897]
[0, 1, 1, 0]
1.0000084040504784
 loss is 0.500004202025
pass 3944
print
[0.         0.99999584 0.         0.0028982 ]
[0, 1, 1, 0]
1.0000083995651083
 loss is 0.500004199783
pass 3945
print
[0.         0.99999584 0.         0.00289742]
[0, 1, 1, 0]
1.0000083950833207
 loss is 0.500004197542
pass 3946
print
[0.         0.99999585 0.         0.00289665]
[0, 1, 1, 0]
1.0000083906051116
 loss is 0.500004195303
pass 3947
print
[0.         0.99999585 0.         0.00289588]
[0, 1, 1, 0]
1.0000083861304772
 loss is 0.500004193065
pass 3948
print
[0.         0.99999585 0.         0.00289511]
[0, 1, 1, 0]
1.0000083816594136
 loss is 0.50000419083
pass 3949
print
[0.         0.99999585 0.         0.00289433]
[0, 1,

1.0000073446459918
 loss is 0.500003672323
pass 4205
print
[0.         0.99999637 0.         0.00270942]
[0, 1, 1, 0]
1.000007340979829
 loss is 0.50000367049
pass 4206
print
[0.         0.99999637 0.         0.00270875]
[0, 1, 1, 0]
1.0000073373164045
 loss is 0.500003668658
pass 4207
print
[0.         0.99999637 0.         0.00270807]
[0, 1, 1, 0]
1.0000073336557167
 loss is 0.500003666828
pass 4208
print
[0.         0.99999637 0.         0.00270739]
[0, 1, 1, 0]
1.0000073299977623
 loss is 0.500003664999
pass 4209
print
[0.         0.99999637 0.         0.00270672]
[0, 1, 1, 0]
1.0000073263425386
 loss is 0.500003663171
pass 4210
print
[0.         0.99999637 0.         0.00270604]
[0, 1, 1, 0]
1.0000073226900428
 loss is 0.500003661345
pass 4211
print
[0.         0.99999638 0.         0.00270537]
[0, 1, 1, 0]
1.0000073190402723
 loss is 0.50000365952
pass 4212
print
[0.         0.99999638 0.         0.0027047 ]
[0, 1, 1, 0]
1.0000073153932247
 loss is 0.500003657697
pass 4213
print


pass 4460
print
[0.         0.99999679 0.         0.00254726]
[0, 1, 1, 0]
1.000006488529663
 loss is 0.500003244265
pass 4461
print
[0.         0.99999679 0.         0.00254666]
[0, 1, 1, 0]
1.000006485484301
 loss is 0.500003242742
pass 4462
print
[0.         0.99999679 0.         0.00254606]
[0, 1, 1, 0]
1.0000064824410788
 loss is 0.500003241221
pass 4463
print
[0.         0.99999679 0.         0.00254546]
[0, 1, 1, 0]
1.000006479399994
 loss is 0.5000032397
pass 4464
print
[0.         0.99999679 0.         0.00254487]
[0, 1, 1, 0]
1.000006476361045
 loss is 0.500003238181
pass 4465
print
[0.         0.9999968  0.         0.00254427]
[0, 1, 1, 0]
1.0000064733242295
 loss is 0.500003236662
pass 4466
print
[0.         0.9999968  0.         0.00254367]
[0, 1, 1, 0]
1.0000064702895453
 loss is 0.500003235145
pass 4467
print
[0.         0.9999968  0.         0.00254308]
[0, 1, 1, 0]
1.0000064672569908
 loss is 0.500003233628
pass 4468
print
[0.         0.9999968  0.         0.00254248]


print
[0.         0.99999715 0.         0.0024007 ]
[0, 1, 1, 0]
1.0000057633848791
 loss is 0.500002881692
pass 4721
print
[0.         0.99999715 0.         0.00240017]
[0, 1, 1, 0]
1.0000057608346251
 loss is 0.500002880417
pass 4722
print
[0.         0.99999715 0.         0.00239964]
[0, 1, 1, 0]
1.0000057582860606
 loss is 0.500002879143
pass 4723
print
[0.         0.99999715 0.         0.00239911]
[0, 1, 1, 0]
1.000005755739184
 loss is 0.50000287787
pass 4724
print
[0.         0.99999715 0.         0.00239858]
[0, 1, 1, 0]
1.0000057531939934
 loss is 0.500002876597
pass 4725
print
[0.         0.99999715 0.         0.00239805]
[0, 1, 1, 0]
1.000005750650488
 loss is 0.500002875325
pass 4726
print
[0.         0.99999715 0.         0.00239752]
[0, 1, 1, 0]
1.0000057481086662
 loss is 0.500002874054
pass 4727
print
[0.         0.99999716 0.         0.00239699]
[0, 1, 1, 0]
1.000005745568526
 loss is 0.500002872784
pass 4728
print
[0.         0.99999716 0.         0.00239646]
[0, 1, 1

pass 4933
print
[0.         0.9999974  0.         0.00229261]
[0, 1, 1, 0]
1.00000525608724
 loss is 0.500002628044
pass 4934
print
[0.         0.9999974  0.         0.00229213]
[0, 1, 1, 0]
1.0000052538656206
 loss is 0.500002626933
pass 4935
print
[0.         0.9999974  0.         0.00229165]
[0, 1, 1, 0]
1.0000052516454068
 loss is 0.500002625823
pass 4936
print
[0.         0.9999974  0.         0.00229116]
[0, 1, 1, 0]
1.0000052494265979
 loss is 0.500002624713
pass 4937
print
[0.         0.9999974  0.         0.00229068]
[0, 1, 1, 0]
1.0000052472091927
 loss is 0.500002623605
pass 4938
print
[0.         0.9999974  0.         0.00229019]
[0, 1, 1, 0]
1.0000052449931895
 loss is 0.500002622497
pass 4939
print
[0.         0.9999974  0.         0.00228971]
[0, 1, 1, 0]
1.0000052427785877
 loss is 0.500002621389
pass 4940
print
[0.         0.99999741 0.         0.00228923]
[0, 1, 1, 0]
1.0000052405653859
 loss is 0.500002620283
pass 4941
print
[0.         0.99999741 0.         0.002288

1.0000048089493014
 loss is 0.500002404475
pass 5149
print
[0.         0.99999762 0.         0.00219249]
[0, 1, 1, 0]
1.0000048070046066
 loss is 0.500002403502
pass 5150
print
[0.         0.99999762 0.         0.00219204]
[0, 1, 1, 0]
1.000004805061089
 loss is 0.500002402531
pass 5151
print
[0.         0.99999762 0.         0.0021916 ]
[0, 1, 1, 0]
1.0000048031187478
 loss is 0.500002401559
pass 5152
print
[0.         0.99999762 0.         0.00219116]
[0, 1, 1, 0]
1.0000048011775826
 loss is 0.500002400589
pass 5153
print
[0.         0.99999762 0.         0.00219071]
[0, 1, 1, 0]
1.000004799237592
 loss is 0.500002399619
pass 5154
print
[0.         0.99999763 0.         0.00219027]
[0, 1, 1, 0]
1.0000047972987751
 loss is 0.500002398649
pass 5155
print
[0.         0.99999763 0.         0.00218983]
[0, 1, 1, 0]
1.0000047953611308
 loss is 0.500002397681
pass 5156
print
[0.         0.99999763 0.         0.00218939]
[0, 1, 1, 0]
1.0000047934246588
 loss is 0.500002396712
pass 5157
print

pass 5369
print
[0.         0.99999782 0.         0.00209909]
[0, 1, 1, 0]
1.0000044062000675
 loss is 0.5000022031
pass 5370
print
[0.         0.99999782 0.         0.00209869]
[0, 1, 1, 0]
1.0000044044941148
 loss is 0.500002202247
pass 5371
print
[0.         0.99999782 0.         0.00209828]
[0, 1, 1, 0]
1.000004402789151
 loss is 0.500002201395
pass 5372
print
[0.         0.99999782 0.         0.00209788]
[0, 1, 1, 0]
1.0000044010851756
 loss is 0.500002200543
pass 5373
print
[0.         0.99999782 0.         0.00209747]
[0, 1, 1, 0]
1.0000043993821877
 loss is 0.500002199691
pass 5374
print
[0.         0.99999782 0.         0.00209706]
[0, 1, 1, 0]
1.0000043976801867
 loss is 0.50000219884
pass 5375
print
[0.         0.99999782 0.         0.00209666]
[0, 1, 1, 0]
1.0000043959791713
 loss is 0.50000219799
pass 5376
print
[0.         0.99999782 0.         0.00209625]
[0, 1, 1, 0]
1.0000043942791415
 loss is 0.50000219714
pass 5377
print
[0.         0.99999783 0.         0.00209585]


print
[0.         0.99999805 0.         0.00198711]
[0, 1, 1, 0]
1.0000039485988315
 loss is 0.500001974299
pass 5661
print
[0.         0.99999805 0.         0.00198674]
[0, 1, 1, 0]
1.0000039471512339
 loss is 0.500001973576
pass 5662
print
[0.         0.99999805 0.         0.00198638]
[0, 1, 1, 0]
1.0000039457044305
 loss is 0.500001972852
pass 5663
print
[0.         0.99999805 0.         0.00198601]
[0, 1, 1, 0]
1.0000039442584214
 loss is 0.500001972129
pass 5664
print
[0.         0.99999805 0.         0.00198565]
[0, 1, 1, 0]
1.0000039428132061
 loss is 0.500001971407
pass 5665
print
[0.         0.99999805 0.         0.00198529]
[0, 1, 1, 0]
1.0000039413687838
 loss is 0.500001970684
pass 5666
print
[0.         0.99999805 0.         0.00198492]
[0, 1, 1, 0]
1.0000039399251541
 loss is 0.500001969963
pass 5667
print
[0.         0.99999805 0.         0.00198456]
[0, 1, 1, 0]
1.0000039384823158
 loss is 0.500001969241
pass 5668
print
[0.         0.99999805 0.         0.0019842 ]
[0, 

 loss is 0.500001804378
pass 5912
print
[0.         0.99999821 0.         0.00189934]
[0, 1, 1, 0]
1.000003607490483
 loss is 0.500001803745
pass 5913
print
[0.         0.99999822 0.         0.00189901]
[0, 1, 1, 0]
1.0000036062260973
 loss is 0.500001803113
pass 5914
print
[0.         0.99999822 0.         0.00189867]
[0, 1, 1, 0]
1.0000036049623753
 loss is 0.500001802481
pass 5915
print
[0.         0.99999822 0.         0.00189834]
[0, 1, 1, 0]
1.0000036036993165
 loss is 0.50000180185
pass 5916
print
[0.         0.99999822 0.         0.00189801]
[0, 1, 1, 0]
1.0000036024369203
 loss is 0.500001801218
pass 5917
print
[0.         0.99999822 0.         0.00189768]
[0, 1, 1, 0]
1.0000036011751867
 loss is 0.500001800588
pass 5918
print
[0.         0.99999822 0.         0.00189734]
[0, 1, 1, 0]
1.0000035999141148
 loss is 0.500001799957
pass 5919
print
[0.         0.99999822 0.         0.00189701]
[0, 1, 1, 0]
1.0000035986537044
 loss is 0.500001799327
pass 5920
print
[0.         0.9999

print
[0.         0.99999836 0.         0.00182112]
[0, 1, 1, 0]
1.0000033164870685
 loss is 0.500001658244
pass 6158
print
[0.         0.99999836 0.         0.00182082]
[0, 1, 1, 0]
1.0000033153723429
 loss is 0.500001657686
pass 6159
print
[0.         0.99999836 0.         0.00182051]
[0, 1, 1, 0]
1.0000033142581783
 loss is 0.500001657129
pass 6160
print
[0.         0.99999836 0.         0.0018202 ]
[0, 1, 1, 0]
1.0000033131445747
 loss is 0.500001656572
pass 6161
print
[0.         0.99999836 0.         0.0018199 ]
[0, 1, 1, 0]
1.0000033120315315
 loss is 0.500001656016
pass 6162
print
[0.         0.99999836 0.         0.00181959]
[0, 1, 1, 0]
1.0000033109190483
 loss is 0.50000165546
pass 6163
print
[0.         0.99999836 0.         0.00181929]
[0, 1, 1, 0]
1.0000033098071246
 loss is 0.500001654904
pass 6164
print
[0.         0.99999836 0.         0.00181898]
[0, 1, 1, 0]
1.0000033086957603
 loss is 0.500001654348
pass 6165
print
[0.         0.99999836 0.         0.00181868]
[0, 1

[0.         0.99999849 0.         0.00174823]
[0, 1, 1, 0]
1.0000030563241356
 loss is 0.500001528162
pass 6406
print
[0.         0.99999849 0.         0.00174795]
[0, 1, 1, 0]
1.0000030553378036
 loss is 0.500001527669
pass 6407
print
[0.         0.99999849 0.         0.00174767]
[0, 1, 1, 0]
1.0000030543519485
 loss is 0.500001527176
pass 6408
print
[0.         0.99999849 0.         0.00174739]
[0, 1, 1, 0]
1.00000305336657
 loss is 0.500001526683
pass 6409
print
[0.         0.99999849 0.         0.00174711]
[0, 1, 1, 0]
1.0000030523816676
 loss is 0.500001526191
pass 6410
print
[0.         0.99999849 0.         0.00174682]
[0, 1, 1, 0]
1.000003051397241
 loss is 0.500001525699
pass 6411
print
[0.         0.99999849 0.         0.00174654]
[0, 1, 1, 0]
1.00000305041329
 loss is 0.500001525207
pass 6412
print
[0.         0.99999849 0.         0.00174626]
[0, 1, 1, 0]
1.0000030494298142
 loss is 0.500001524715
pass 6413
print
[0.         0.99999849 0.         0.00174598]
[0, 1, 1, 0]
1.

[0, 1, 1, 0]
1.000002835254906
 loss is 0.500001417627
pass 6643
print
[0.         0.9999986  0.         0.00168356]
[0, 1, 1, 0]
1.000002834373498
 loss is 0.500001417187
pass 6644
print
[0.        0.9999986 0.        0.0016833]
[0, 1, 1, 0]
1.0000028334925006
 loss is 0.500001416746
pass 6645
print
[0.         0.9999986  0.         0.00168304]
[0, 1, 1, 0]
1.0000028326119133
 loss is 0.500001416306
pass 6646
print
[0.         0.9999986  0.         0.00168277]
[0, 1, 1, 0]
1.000002831731736
 loss is 0.500001415866
pass 6647
print
[0.         0.9999986  0.         0.00168251]
[0, 1, 1, 0]
1.0000028308519682
 loss is 0.500001415426
pass 6648
print
[0.         0.9999986  0.         0.00168225]
[0, 1, 1, 0]
1.00000282997261
 loss is 0.500001414986
pass 6649
print
[0.         0.9999986  0.         0.00168199]
[0, 1, 1, 0]
1.000002829093661
 loss is 0.500001414547
pass 6650
print
[0.         0.9999986  0.         0.00168173]
[0, 1, 1, 0]
1.000002828215121
 loss is 0.500001414108
pass 6651
p

pass 6877
print
[0.         0.99999869 0.         0.00162447]
[0, 1, 1, 0]
1.0000026388890078
 loss is 0.500001319445
pass 6878
print
[0.         0.99999869 0.         0.00162422]
[0, 1, 1, 0]
1.0000026380974545
 loss is 0.500001319049
pass 6879
print
[0.         0.99999869 0.         0.00162398]
[0, 1, 1, 0]
1.0000026373062565
 loss is 0.500001318653
pass 6880
print
[0.         0.9999987  0.         0.00162373]
[0, 1, 1, 0]
1.0000026365154144
 loss is 0.500001318258
pass 6881
print
[0.         0.9999987  0.         0.00162349]
[0, 1, 1, 0]
1.0000026357249272
 loss is 0.500001317862
pass 6882
print
[0.         0.9999987  0.         0.00162325]
[0, 1, 1, 0]
1.0000026349347952
 loss is 0.500001317467
pass 6883
print
[0.        0.9999987 0.        0.001623 ]
[0, 1, 1, 0]
1.000002634145018
 loss is 0.500001317073
pass 6884
print
[0.         0.9999987  0.         0.00162276]
[0, 1, 1, 0]
1.0000026333555956
 loss is 0.500001316678
pass 6885
print
[0.         0.9999987  0.         0.00162252]

pass 7098
print
[0.         0.99999878 0.         0.00157234]
[0, 1, 1, 0]
1.0000024722391976
 loss is 0.50000123612
pass 7099
print
[0.         0.99999878 0.         0.00157211]
[0, 1, 1, 0]
1.0000024715213425
 loss is 0.500001235761
pass 7100
print
[0.         0.99999878 0.         0.00157188]
[0, 1, 1, 0]
1.0000024708037998
 loss is 0.500001235402
pass 7101
print
[0.         0.99999878 0.         0.00157165]
[0, 1, 1, 0]
1.000002470086569
 loss is 0.500001235043
pass 7102
print
[0.         0.99999878 0.         0.00157142]
[0, 1, 1, 0]
1.0000024693696503
 loss is 0.500001234685
pass 7103
print
[0.         0.99999878 0.         0.00157119]
[0, 1, 1, 0]
1.000002468653043
 loss is 0.500001234327
pass 7104
print
[0.         0.99999878 0.         0.00157097]
[0, 1, 1, 0]
1.0000024679367476
 loss is 0.500001233968
pass 7105
print
[0.         0.99999878 0.         0.00157074]
[0, 1, 1, 0]
1.0000024672207632
 loss is 0.50000123361
pass 7106
print
[0.         0.99999878 0.         0.00157051

pass 7348
print
[0.         0.99999886 0.         0.00151725]
[0, 1, 1, 0]
1.0000023020489295
 loss is 0.500001151024
pass 7349
print
[0.         0.99999886 0.         0.00151704]
[0, 1, 1, 0]
1.0000023014038277
 loss is 0.500001150702
pass 7350
print
[0.         0.99999886 0.         0.00151682]
[0, 1, 1, 0]
1.0000023007589969
 loss is 0.500001150379
pass 7351
print
[0.         0.99999886 0.         0.00151661]
[0, 1, 1, 0]
1.0000023001144362
 loss is 0.500001150057
pass 7352
print
[0.         0.99999886 0.         0.0015164 ]
[0, 1, 1, 0]
1.0000022994701465
 loss is 0.500001149735
pass 7353
print
[0.         0.99999886 0.         0.00151619]
[0, 1, 1, 0]
1.000002298826127
 loss is 0.500001149413
pass 7354
print
[0.         0.99999886 0.         0.00151598]
[0, 1, 1, 0]
1.0000022981823777
 loss is 0.500001149091
pass 7355
print
[0.         0.99999886 0.         0.00151576]
[0, 1, 1, 0]
1.0000022975388985
 loss is 0.500001148769
pass 7356
print
[0.         0.99999886 0.         0.00151

[0.         0.99999895 0.         0.00145917]
[0, 1, 1, 0]
1.0000021291781926
 loss is 0.500001064589
pass 7633
print
[0.         0.99999895 0.         0.00145897]
[0, 1, 1, 0]
1.0000021286042968
 loss is 0.500001064302
pass 7634
print
[0.         0.99999895 0.         0.00145878]
[0, 1, 1, 0]
1.000002128030633
 loss is 0.500001064015
pass 7635
print
[0.         0.99999895 0.         0.00145858]
[0, 1, 1, 0]
1.0000021274572006
 loss is 0.500001063729
pass 7636
print
[0.         0.99999895 0.         0.00145838]
[0, 1, 1, 0]
1.0000021268839998
 loss is 0.500001063442
pass 7637
print
[0.         0.99999895 0.         0.00145819]
[0, 1, 1, 0]
1.0000021263110306
 loss is 0.500001063156
pass 7638
print
[0.         0.99999895 0.         0.00145799]
[0, 1, 1, 0]
1.0000021257382923
 loss is 0.500001062869
pass 7639
print
[0.         0.99999895 0.         0.00145779]
[0, 1, 1, 0]
1.0000021251657851
 loss is 0.500001062583
pass 7640
print
[0.         0.99999895 0.         0.0014576 ]
[0, 1, 1, 0

pass 7892
print
[0.         0.99999902 0.         0.00140976]
[0, 1, 1, 0]
1.0000019874224237
 loss is 0.500000993711
pass 7893
print
[0.         0.99999902 0.         0.00140958]
[0, 1, 1, 0]
1.000001986904817
 loss is 0.500000993452
pass 7894
print
[0.         0.99999902 0.         0.00140939]
[0, 1, 1, 0]
1.0000019863874121
 loss is 0.500000993194
pass 7895
print
[0.         0.99999902 0.         0.00140921]
[0, 1, 1, 0]
1.0000019858702092
 loss is 0.500000992935
pass 7896
print
[0.         0.99999902 0.         0.00140903]
[0, 1, 1, 0]
1.0000019853532078
 loss is 0.500000992677
pass 7897
print
[0.         0.99999902 0.         0.00140884]
[0, 1, 1, 0]
1.0000019848364083
 loss is 0.500000992418
pass 7898
print
[0.         0.99999902 0.         0.00140866]
[0, 1, 1, 0]
1.0000019843198105
 loss is 0.50000099216
pass 7899
print
[0.         0.99999902 0.         0.00140848]
[0, 1, 1, 0]
1.000001983803414
 loss is 0.500000991902
pass 7900
print
[0.         0.99999902 0.         0.0014082

1.000001851879495
 loss is 0.50000092594
pass 8169
print
[0.         0.99999908 0.         0.00136067]
[0, 1, 1, 0]
1.0000018514138738
 loss is 0.500000925707
pass 8170
print
[0.         0.99999908 0.         0.0013605 ]
[0, 1, 1, 0]
1.0000018509484276
 loss is 0.500000925474
pass 8171
print
[0.         0.99999908 0.         0.00136032]
[0, 1, 1, 0]
1.000001850483157
 loss is 0.500000925242
pass 8172
print
[0.         0.99999908 0.         0.00136015]
[0, 1, 1, 0]
1.0000018500180612
 loss is 0.500000925009
pass 8173
print
[0.         0.99999908 0.         0.00135998]
[0, 1, 1, 0]
1.0000018495531409
 loss is 0.500000924777
pass 8174
print
[0.         0.99999909 0.         0.00135981]
[0, 1, 1, 0]
1.0000018490883955
 loss is 0.500000924544
pass 8175
print
[0.         0.99999909 0.         0.00135964]
[0, 1, 1, 0]
1.0000018486238251
 loss is 0.500000924312
pass 8176
print
[0.         0.99999909 0.         0.00135947]
[0, 1, 1, 0]
1.0000018481594297
 loss is 0.50000092408
pass 8177
print
[

pass 8470
print
[0.         0.99999915 0.         0.00131105]
[0, 1, 1, 0]
1.0000017188522938
 loss is 0.500000859426
pass 8471
print
[0.         0.99999915 0.         0.00131089]
[0, 1, 1, 0]
1.000001718435883
 loss is 0.500000859218
pass 8472
print
[0.         0.99999915 0.         0.00131073]
[0, 1, 1, 0]
1.0000017180196232
 loss is 0.50000085901
pass 8473
print
[0.         0.99999915 0.         0.00131057]
[0, 1, 1, 0]
1.000001717603515
 loss is 0.500000858802
pass 8474
print
[0.         0.99999915 0.         0.00131041]
[0, 1, 1, 0]
1.0000017171875573
 loss is 0.500000858594
pass 8475
print
[0.         0.99999915 0.         0.00131026]
[0, 1, 1, 0]
1.000001716771751
 loss is 0.500000858386
pass 8476
print
[0.         0.99999915 0.         0.0013101 ]
[0, 1, 1, 0]
1.000001716356095
 loss is 0.500000858178
pass 8477
print
[0.         0.99999915 0.         0.00130994]
[0, 1, 1, 0]
1.0000017159405903
 loss is 0.50000085797
pass 8478
print
[0.         0.99999915 0.         0.00130978]


pass 8722
print
[0.         0.9999992  0.         0.00127221]
[0, 1, 1, 0]
1.000001618511641
 loss is 0.500000809256
pass 8723
print
[0.         0.9999992  0.         0.00127206]
[0, 1, 1, 0]
1.0000016181311215
 loss is 0.500000809066
pass 8724
print
[0.         0.9999992  0.         0.00127191]
[0, 1, 1, 0]
1.0000016177507358
 loss is 0.500000808875
pass 8725
print
[0.         0.9999992  0.         0.00127176]
[0, 1, 1, 0]
1.0000016173704844
 loss is 0.500000808685
pass 8726
print
[0.         0.9999992  0.         0.00127161]
[0, 1, 1, 0]
1.0000016169903672
 loss is 0.500000808495
pass 8727
print
[0.         0.9999992  0.         0.00127146]
[0, 1, 1, 0]
1.0000016166103833
 loss is 0.500000808305
pass 8728
print
[0.         0.9999992  0.         0.00127131]
[0, 1, 1, 0]
1.0000016162305334
 loss is 0.500000808115
pass 8729
print
[0.         0.9999992  0.         0.00127116]
[0, 1, 1, 0]
1.0000016158508174
 loss is 0.500000807925
pass 8730
print
[0.         0.9999992  0.         0.00127

[0.         0.99999924 0.         0.00123602]
[0, 1, 1, 0]
1.0000015277469403
 loss is 0.500000763873
pass 8972
print
[0.         0.99999924 0.         0.00123588]
[0, 1, 1, 0]
1.0000015273979475
 loss is 0.500000763699
pass 8973
print
[0.         0.99999924 0.         0.00123574]
[0, 1, 1, 0]
1.0000015270490739
 loss is 0.500000763525
pass 8974
print
[0.         0.99999924 0.         0.0012356 ]
[0, 1, 1, 0]
1.0000015267003197
 loss is 0.50000076335
pass 8975
print
[0.         0.99999924 0.         0.00123546]
[0, 1, 1, 0]
1.000001526351685
 loss is 0.500000763176
pass 8976
print
[0.         0.99999924 0.         0.00123531]
[0, 1, 1, 0]
1.0000015260031694
 loss is 0.500000763002
pass 8977
print
[0.         0.99999925 0.         0.00123517]
[0, 1, 1, 0]
1.0000015256547732
 loss is 0.500000762827
pass 8978
print
[0.         0.99999925 0.         0.00123503]
[0, 1, 1, 0]
1.000001525306496
 loss is 0.500000762653
pass 8979
print
[0.         0.99999925 0.         0.00123489]
[0, 1, 1, 0]


pass 9225
print
[0.         0.99999929 0.         0.00120117]
[0, 1, 1, 0]
1.0000014427992179
 loss is 0.5000007214
pass 9226
print
[0.         0.99999929 0.         0.00120103]
[0, 1, 1, 0]
1.0000014424788983
 loss is 0.500000721239
pass 9227
print
[0.         0.99999929 0.         0.0012009 ]
[0, 1, 1, 0]
1.0000014421586851
 loss is 0.500000721079
pass 9228
print
[0.         0.99999929 0.         0.00120077]
[0, 1, 1, 0]
1.0000014418385788
 loss is 0.500000720919
pass 9229
print
[0.         0.99999929 0.         0.00120063]
[0, 1, 1, 0]
1.0000014415185787
 loss is 0.500000720759
pass 9230
print
[0.         0.99999929 0.         0.0012005 ]
[0, 1, 1, 0]
1.000001441198685
 loss is 0.500000720599
pass 9231
print
[0.         0.99999929 0.         0.00120037]
[0, 1, 1, 0]
1.0000014408788978
 loss is 0.500000720439
pass 9232
print
[0.         0.99999929 0.         0.00120023]
[0, 1, 1, 0]
1.0000014405592168
 loss is 0.50000072028
pass 9233
print
[0.         0.99999929 0.         0.0012001 

pass 9501
print
[0.         0.99999933 0.         0.00116545]
[0, 1, 1, 0]
1.0000013582774883
 loss is 0.500000679139
pass 9502
print
[0.         0.99999933 0.         0.00116533]
[0, 1, 1, 0]
1.0000013579848754
 loss is 0.500000678992
pass 9503
print
[0.         0.99999933 0.         0.0011652 ]
[0, 1, 1, 0]
1.000001357692357
 loss is 0.500000678846
pass 9504
print
[0.         0.99999933 0.         0.00116507]
[0, 1, 1, 0]
1.000001357399933
 loss is 0.5000006787
pass 9505
print
[0.         0.99999933 0.         0.00116495]
[0, 1, 1, 0]
1.0000013571076034
 loss is 0.500000678554
pass 9506
print
[0.         0.99999933 0.         0.00116482]
[0, 1, 1, 0]
1.0000013568153683
 loss is 0.500000678408
pass 9507
print
[0.         0.99999933 0.         0.0011647 ]
[0, 1, 1, 0]
1.0000013565232273
 loss is 0.500000678262
pass 9508
print
[0.         0.99999933 0.         0.00116457]
[0, 1, 1, 0]
1.0000013562311807
 loss is 0.500000678116
pass 9509
print
[0.         0.99999933 0.         0.00116445

pass 9749
print
[0.         0.99999936 0.         0.00113512]
[0, 1, 1, 0]
1.0000012885040077
 loss is 0.500000644252
pass 9750
print
[0.         0.99999936 0.         0.001135  ]
[0, 1, 1, 0]
1.0000012882336307
 loss is 0.500000644117
pass 9751
print
[0.         0.99999936 0.         0.00113488]
[0, 1, 1, 0]
1.0000012879633389
 loss is 0.500000643982
pass 9752
print
[0.         0.99999936 0.         0.00113477]
[0, 1, 1, 0]
1.0000012876931317
 loss is 0.500000643847
pass 9753
print
[0.         0.99999936 0.         0.00113465]
[0, 1, 1, 0]
1.0000012874230095
 loss is 0.500000643712
pass 9754
print
[0.         0.99999936 0.         0.00113453]
[0, 1, 1, 0]
1.0000012871529724
 loss is 0.500000643576
pass 9755
print
[0.         0.99999936 0.         0.00113441]
[0, 1, 1, 0]
1.0000012868830201
 loss is 0.500000643442
pass 9756
print
[0.         0.99999936 0.         0.00113429]
[0, 1, 1, 0]
1.0000012866131527
 loss is 0.500000643307
pass 9757
print
[0.         0.99999936 0.         0.0011

pass 9961
print
[0.         0.99999939 0.         0.00111042]
[0, 1, 1, 0]
1.0000012330314298
 loss is 0.500000616516
pass 9962
print
[0.         0.99999939 0.         0.00111031]
[0, 1, 1, 0]
1.0000012327783092
 loss is 0.500000616389
pass 9963
print
[0.         0.99999939 0.         0.00111019]
[0, 1, 1, 0]
1.0000012325252667
 loss is 0.500000616263
pass 9964
print
[0.         0.99999939 0.         0.00111008]
[0, 1, 1, 0]
1.000001232272302
 loss is 0.500000616136
pass 9965
print
[0.         0.99999939 0.         0.00110996]
[0, 1, 1, 0]
1.000001232019415
 loss is 0.50000061601
pass 9966
print
[0.         0.99999939 0.         0.00110985]
[0, 1, 1, 0]
1.0000012317666058
 loss is 0.500000615883
pass 9967
print
[0.         0.99999939 0.         0.00110974]
[0, 1, 1, 0]
1.0000012315138744
 loss is 0.500000615757
pass 9968
print
[0.         0.99999939 0.         0.00110962]
[0, 1, 1, 0]
1.0000012312612205
 loss is 0.500000615631
pass 9969
print
[0.         0.99999939 0.         0.0011095

In [279]:
# input data( shape 2*1 ) to calculate answer
inp=[[1],[1]]
nn.forward_prop(inp)

{1: array([[ 1.13858817, -0.80163087],
        [ 0.685869  ,  0.29734185]]), 2: array([ 1.10591159, -0.37788334])}

In [215]:
print("weigths: layer 0 and 1")
print(nn.weights[1])
print("weigths: layer 1 and 2")
print(nn.weights[2])

weigths: layer 0 and 1
[[-1.24858902 -0.76986153]
 [13.00405634 16.90627723]]
weigths: layer 1 and 2
[-0.02065439  8.3389418 ]


In [276]:
#plot loss 
nn.loss

array([0.00183334])

[0.702379250762237,
 0.7078615614501016,
 0.7134306764853708,
 0.7188918574843024,
 0.7241701056571123,
 0.7292433784877871,
 0.7308158673327518,
 0.7276713978807092,
 0.724637691069005,
 0.7216681377605875,
 0.7187308843957738,
 0.7158039873820566,
 0.7128723445816854,
 0.7099256973395358,
 0.706957298140929,
 0.7039630034661263,
 0.7009406445619165,
 0.6978895833820784,
 0.6948103938117118,
 0.6917046286133841,
 0.6885746453971465,
 0.6854234732364175,
 0.6822547070453052,
 0.6790724205379068,
 0.6758810911477983,
 0.672685532100962,
 0.6694908281676479,
 0.6663022726372418,
 0.6631253038757774,
 0.6599654405097813,
 0.6568282148771691,
 0.6537191049206318,
 0.6506434651812835,
 0.6476064579788219,
 0.6446129862290101,
 0.641667629634083,
 0.6387745861678545,
 0.6359376208462084,
 0.6331600237101922,
 0.6304445787447973,
 0.6277935451131051,
 0.625208651615924,
 0.6226911047169251,
 0.6202416098397835,
 0.6178604049931573,
 0.6155473051626228,
 0.6133017553766718,
 0.6111228899513363

part 2

In [209]:
# generate data


In [79]:
numHideenNeuron= 10
n= numHideenNeuron
nn= xor(n)
# x, y, learning_rate
nn.train(inp,out,500)

matrix([[1, 2]])

Notes: For backpropagation, I am using the method from Prof. Iddo notes. 

In [255]:
1.2074946414242518/2

0.6037473207121259