In [210]:
import random as rd
import numpy as np

In [240]:
class xor():
    def __init__(self,n): 
        # n is the number of neurons in the hidden layer
        self.layers_Z={1:[] , 2:[]}
        self.layers_A={0:[], 1:[] , 2:[]}
        self.weights={1:[[rd.uniform(-1, 1) for i in range(2)] for j in range(n)], 
                     2:[rd.uniform(-1, 1) for i in range(n)]}
        self.b= {1: [[0],[0]] , 2:[0]}
        self.activation= "relu"
        self.loss=[]  # plot this loss afterwards
        
    def affineForward(self,x, w, b):
        return np.dot(self.weights[w],x) + self.b[b]

    
    def activationForward(self, A):


        if self.activation == "sig":
            A = self.sigmoid(A)
        elif self.activation == "relu":
            A = self.relu(A)
        return A
    
    def sigmoid(self, X):
        x = X.copy()
        out = 1/(1 + np.exp(-x))
        return out
    
    def relu(self, X):
        activation = np.maximum(0,X)
        return activation
    
    def lossfunction(self, y_hat, y ):
        print("print")
        print sum((y_hat-y)**2)
        loss = 1/2*sum((y_hat-y)**2)

        
        dAL = y_hat - y
        return loss, dAL
            
        
    
    def forward_prop(self,data):
#         inp= [[0, 1],[1,1]]
#         out=out
        self.layers_A[0]= data
        self.layers_Z[1]= self.affineForward(self.layers_A[0],1,1)
        self.layers_A[1]= self.activationForward(self.layers_Z[1])
        self.layers_Z[2]= self.affineForward(self.layers_A[1],2,2)
        self.layers_A[2]=self.activationForward(self.layers_Z[2])
        return self.layers_A[2]
    
    def background_prop(self, target, alpha):
        loss, dA_2= self.lossfunction(self.layers_A[2],target)
        self.loss.append(loss)
        print(" loss is "+ str(loss))
        gZ_2= self.G_Z(self.layers_Z[2])
        dZ_2= dA_2 * gZ_2

        dA_1= np.dot(np.matrix(self.weights[2]).T, np.matrix(dZ_2))
        
        dW_2= np.dot(np.matrix(dZ_2), np.matrix(self.layers_A[1]).T)
        dW_2= np.array(dW_2)[0]

        gZ_1= self.G_Z(self.layers_Z[1],)
        
        dZ_1= np.array(dA_1) * np.array(gZ_1)
        
        dA_0= np.dot(np.matrix(self.weights[1]).T, np.matrix(dZ_1))
        
        
        dW_1= np.dot(np.matrix(dZ_1), np.matrix(self.layers_A[0]).T)
        dW_1= np.array(dW_1)

        
#         print(alpha * dW_2)
#         print(alpha * dW_1)
        # update weights
        self.weights[2] = self.weights[2] - alpha * dW_2
        self.weights[1] = self.weights[1] - alpha * dW_1
        
        return 1
        
    def G_Z(self, Z):
        x = Z.copy()
        if self.activation == "sig":
            out = np.exp(-x)/((1 + np.exp(-x))**2)
        elif self.activation == "relu":
            out = x * 1 * (x > 0)
        return out        
        
        
        return out
    
    
    def train(self, data, out,alpha):
        for i in range(10):
            print("pass "+ str(i))
            
            self.forward_prop(data)       
            self.background_prop(out, alpha)
            


In [241]:
out=[0,1,1,0]
inp= [[0,0,1,1],[0,1,0,1]]

In [242]:
out=[1,0]
inp= [[0,1],[1,1]]
nn= xor(2)
# nn.forward_prop(inp, out)
nn.train(inp,out,500)

pass 0
print
1.0
 loss is 0.0
pass 1
print
1.0
 loss is 0.0
pass 2
print
1.0
 loss is 0.0
pass 3
print
1.0
 loss is 0.0
pass 4
print
1.0
 loss is 0.0
pass 5
print
1.0
 loss is 0.0
pass 6
print
1.0
 loss is 0.0
pass 7
print
1.0
 loss is 0.0
pass 8
print
1.0
 loss is 0.0
pass 9
print
1.0
 loss is 0.0


In [230]:
out=[1,1]
inp= [[0,1],[1,0]]
nn.train(inp,out,500)

pass 0
[0.         0.43717943]
[1, 1]
 loss is 0.0
pass 1
[   0.         4910.78389955]
[1, 1]
 loss is 0.0
pass 2
[0. 0.]
[1, 1]
 loss is 0.0
pass 3
[0. 0.]
[1, 1]
 loss is 0.0
pass 4
[0. 0.]
[1, 1]
 loss is 0.0
pass 5
[0. 0.]
[1, 1]
 loss is 0.0
pass 6
[0. 0.]
[1, 1]
 loss is 0.0
pass 7
[0. 0.]
[1, 1]
 loss is 0.0
pass 8
[0. 0.]
[1, 1]
 loss is 0.0
pass 9
[0. 0.]
[1, 1]
 loss is 0.0


In [215]:
print("weigths: layer 0 and 1")
print(nn.weights[1])
print("weigths: layer 1 and 2")
print(nn.weights[2])

weigths: layer 0 and 1
[[-1.24858902 -0.76986153]
 [13.00405634 16.90627723]]
weigths: layer 1 and 2
[-0.02065439  8.3389418 ]


In [119]:
# input data( shape 2*1 ) to calculate answer
inp=[[0],[0]]
nn.forward_prop(inp)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [69]:
#plot loss 

array([2, 4])

part 2

In [209]:
# generate data


In [79]:
numHideenNeuron= 10
n= numHideenNeuron
nn= xor(n)
# x, y, learning_rate
nn.train(inp,out,500)

matrix([[1, 2]])

Notes: For backpropagation, I am using the method from Prof. Iddo notes. 