# CS-GY 9223-E: Deep Learning Homework 1
Due on Sunday, 11th February 2018, 11:55 PM

This homework can be done in pairs. Everyone must submit on NYU Classes individually.

Write down the UNIs (NetIDs) of your group (if applicable)

Member 1: Name, NetID

Member 2: Name, NetID

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import scipy.misc
import glob
import sys
# you shouldn't need to make any more imports

In [43]:
class NeuralNetwork(object):
    """
    Abstraction of neural network.
    Stores parameters, activations, cached values. 
    Provides necessary functions for training and prediction. 
    """
    def __init__(self, layer_dimensions, drop_prob=0.0, reg_lambda=0.0, activation="relu"):
        """
        Initializes the weights and biases for each layer
        :param layer_dimensions: (list) number of nodes in each layer
        :param drop_prob: drop probability for dropout layers. Only required in part 2 of the assignment
        :param reg_lambda: regularization parameter. Only required in part 2 of the assignment
        """
        np.random.seed(1)
        
        self.parameters = {}
        self.num_layers = 3
        self.layer_dimensions = layer_dimensions
        self.drop_prob = drop_prob
        self.reg_lambda = reg_lambda
        self.activation = activation
        self.train_cost = []
        self.val_cost = []
        self.train_accuracy = []
        self.val_accuracy = []
        self.cost=[]
        
        # init parameters        
        model = {}
        
        for i in range(len(layer_dimensions) - 1):
            layer_ahead = layer_dimensions[i+1]
            layer_behind = layer_dimensions[i]
            model['W'+str(i+1)] = np.random.randn(layer_ahead, layer_behind) * np.sqrt(2.0/(layer_ahead+layer_behind))
            model['b'+str(i+1)] = np.zeros((layer_ahead,1))
            
        self.parameters = model

    def affineForward(self, A, W, b):
        """
        Forward pass for the affine layer.
        :param A: input matrix, shape (L, S), where L is the number of hidden units in the previous layer and S is
        the number of samples
        :returns: the affine product WA + b, along with the cache required for the backward pass
        """
        samples = A.shape[1]
        features = A.shape[0]
        
        Z = np.dot(W,A) + b
        return Z

    def activationForward(self, A):
        """
        Common interface to access all activation functions.
        :param A: input to the activation function
        :param prob: activation funciton to apply to A. Just "relu" for this assignment.
        :returns: activation(A)
        """ 
        if self.activation == "relu":
            A = self.relu(A)
        elif self.activation == "lrelu":
            A = self.leaky_relu(A,0.1)
        return A


    def relu(self, X):
        activation = np.maximum(0,X)
        return activation
    
    def leaky_relu(self, X, alpha):
        x = X.copy()
        out = self.relu(x) - alpha * self.relu(-x)
        return out
        
    def swish(self, X):
        x = X.copy()
        out = x * self.sigmoid(x)
        return out
        
    def sigmoid(self, X):
        x = X.copy()
        out = 1/(1 + np.exp(-x))
        return out
            
    def softmax(self, X):
        S = X - np.amax(X, axis=0)
        S = np.exp(S)
        total = np.sum(S,axis=0, keepdims=True)
        soft_m = S/total
        
        return soft_m
##    
    def dropout(self, A, prob):
        """
        :param A: Activation
        :param prob: drop prob
        :returns: tuple (A, M) 
            WHERE
            A is matrix after applying dropout
            M is dropout mask, used in the backward pass
        """
        M = np.random.rand(A.shape[0], A.shape[1])
        M = (M >= prob)*1.0
        M /= (1- prob)
        A *= M
        return A, M
##

    def forwardPropagation(self, X):
        """
        Runs an input X through the neural network to compute activations
        for all layers. Returns the output computed at the last layer along
        with the cache required for backpropagation.
        :returns: (tuple) AL, cache
            WHERE 
            AL is activation of last layer
            cache is cached values for each layer that
                     are needed in further steps
        """
        cache = {}
        cache['A' + str(0)] = X
        ls = self.num_layers
        
        for i in range(ls - 2):
            W = self.parameters['W' + str(i+1)]
            b = self.parameters['b' + str(i+1)]
            A = cache['A' + str(i)]
            Z = self.affineForward(A, W, b)
            A_next = self.activationForward(Z)
##            
            # adding dropout here
            if self.drop_prob > 0 :
                A_next, M = self.dropout(A_next, self.drop_prob)
                cache['M' + str(i+1)] = M            
##        
            cache['A'+str(i+1)] = A_next
            cache['Z'+str(i+1)] = Z
        
        W = self.parameters['W'+str(ls-1)]
        b = self.parameters['b'+str(ls-1)]
        A_class = cache['A'+str(ls-2)]
        
        AL = self.affineForward(A_class, W, b) #without softmax. softmax will be applied while calculating the cost function
        
        return AL, cache
    
    def costFunction(self, y_hat, y):


        loss = (y_hat-y)**2
        s=0
        print(loss)
        for i in loss:
            s=s+i
        loss= s/2
        self.cost.append(loss)
        
        dAL = y_hat - y
        return loss, dAL


    def affineBackward(self, dA_prev, cache, layer):
        """
        Backward pass for the affine layer.
        :param dA_prev: gradient from the next layer.
        :param cache: cache returned in affineForward
        :returns dA: gradient on the input to this layer
                 dW: gradient on the weights
                 db: gradient on the bias
        """
        A = cache['A'+str(layer-1)]
        W = self.parameters['W'+str(layer)]
        samples = dA_prev.shape[1]
##        
        #add dropout back propagation here
        if self.drop_prob > 0:
            dA_prev = self.dropout_backward(dA_prev, cache, layer)
 ##       
        dZ = self.activationBackward(dA_prev, cache, layer, "relu")
        dW = 1/samples * np.dot(dZ, A.T)
        db = 1/samples * np.sum(dZ, axis = 1, keepdims = True)
        dA = np.dot(W.T, dZ)
        
        return dA, dW, db

    def activationBackward(self, dA, cache, layer, activation):
        """
        Interface to call backward on activation functions.
        In this case, it's just relu. 
        """
        Z = cache['Z'+str(layer)]
        if activation == "relu":
            dx = self.relu_derivative(dA, Z)
        elif activation == "lrelu":
            dx = self.lrelu_derivative(dA, Z, 0.1)
        return dx
    
    def relu_derivative(self, dx, cached_x):
        dA = dx * 1 * (cached_x > 0)
        return dA

    def lrelu_derivative(self, dx, cached_x, alpha):
        dA = np.ones_like(cached_x)
        dA[cached_x < 0] = alpha
        return dA*dx
##    
    def dropout_backward(self, dA, cache, layer):
        m= cache['M' + str(layer)]
        return np.multiply(m, dA) / (1 - self.drop_prob)
##
    def backPropagation(self, dAL, AL, cache):
        """
        Run backpropagation to compute gradients on all paramters in the model
        :param dAL: gradient on the last layer of the network. Returned by the cost function.
        :param Y: labels
        :param cache: cached values during forwardprop
        :returns gradients: dW and db for each weight/bias
        """
        gradients = {}
        
        m = AL.shape[1]
        
        samples = AL.shape[1]
        features = AL.shape[0]
        layers = self.num_layers
        
        #computing gradients using error at the output, bias at the output, and the weight matrix immediately before
        A = cache['A' + str(layers - 2)] # Activations at the layer previous layer
        W = self.parameters['W' + str(layers - 1)]
        dZ = dAL
        dW = 1/samples * np.dot(dZ, A.T)
        db = 1/samples * np.sum(dZ, axis = 1, keepdims = True)
        dA = np.dot(W.T, dZ)
        
        gradients['dW' + str(self.num_layers - 1)] = dW
        gradients['db' + str(self.num_layers - 1)] = db
        
        
        for layer in range(layers-2,0,-1):
            dA, dW, db = self.affineBackward(dA, cache, layer)
            gradients['dW' + str(layer)] = dW
            gradients['db' + str(layer)] = db
##            

            
        if self.reg_lambda > 0:
            # add gradients from L2 regularization to each dW
            for i in range(self.num_layers - 2):
                dW = gradients['dW' + str(i + 1)]
                W = self.parameters['W' + str(i + 1)]
                dW_updated = dW + self.reg_lambda / m * W
                gradients['dW' + str(i + 1)] = dW_updated
##        
        return gradients


    def updateParameters(self, gradients, alpha):
        """
        :param gradients: gradients for each weight/bias
        :param alpha: step size for gradient descent 
        """
        for l in range(1, self.num_layers):
            self.parameters["W" + str(l)] = self.parameters["W" + str(l)] - alpha * gradients["dW" + str(l)]
            self.parameters["b" + str(l)] = self.parameters["b" + str(l)] - alpha * gradients["db" + str(l)]
        
    def train(self, X, y, iters=1000, alpha=0.001, batch_size=100, print_every=100):
        
        
        for i in range(0, iters):
            X_batch= X
            y_batch=y
            
            # forward prop
            AL, cache = self.forwardPropagation(X_batch)
            
            # compute loss
            cost, dAL = self.costFunction(AL, y_batch)

            # compute gradients
            gradients = self.backPropagation(dAL, AL, cache)

            # update weights and biases based on gradient
            self.updateParameters(gradients, alpha)
    


            if i % print_every == 0:
                
                if i % 500 == 0 and i != 0:
                    alpha /= 2


                print("prediction on the training set" )
                v_pred = self.predict(X_batch)
                print(v_pred)
                for i in range(len(v_pred)):
                    if v_pred[i]>=0.5:
                        v_pred[i]=1
                    else:
                        v_pred[i]=0
                print("% inaccuracy")
                c=0  
                for i in range(len(v_pred)):
                    if v_pred[i]!=y_batch[i]:
                        c= c+1
                print(float(c)/len(v_pred)*100)

                
                
    def predict(self, X):
        """
        Make predictions for each sample
        """
        AL, _ = self.forwardPropagation(X)
        y_pred = np.argmax(AL, axis=0)
        
        return y_pred


In [44]:
# Load the data


## Part 1

#### Simple fully-connected deep neural network

In [45]:
layer_dimensions = [2,2,1]  # including the input and output layers
NN = NeuralNetwork(layer_dimensions, 0.2, 0.1,'relu')
y_train=np.array([0,1,1,0])
X_train= np.array([[0,0,1,1],[0,1,0,1]])
NN.train(X_train, y_train, iters=20000, alpha=0.3, print_every=1000)

[[0.00000000e+00 1.00000000e+00 2.10008025e-04 3.99950808e-01]]
prediction on the training set
[0 0 0 0]
% inaccuracy
50.0
[[0.         1.         1.         0.39397404]]
[[0.00000000e+00 1.00000000e+00 4.47100854e-07 3.88086593e-01]]
[[0.         1.         1.         0.38228712]]
[[0.00000000e+00 1.00000000e+00 2.43435316e-04 3.76574321e-01]]
[[0.         1.         1.         0.37094689]]
[[0.00000000e+00 1.00000000e+00 9.18878285e-04 3.65403551e-01]]
[[0.         1.         0.00141268 0.35994305]]
[[0.         1.         0.00200738 0.35456415]]
[[0.         1.         0.00270065 0.34926563]]
[[0.         1.         0.00349021 0.3440463 ]]
[[0.         1.         0.00437382 0.33890495]]
[[0.         1.         0.0053493  0.33384044]]
[[0.         1.         0.00641446 0.32885162]]
[[0.        1.        0.0075672 0.       ]]
[[0.         1.         0.00880543 0.        ]]
[[0.         1.         0.01012709 0.        ]]
[[0.         1.         1.         0.30963076]]
[[0. 1. 1. 0.]]
[

[[0.0000000e+00 1.0000000e+00 9.4275616e-01 3.2780317e-04]]
[[0.00000000e+00 1.00000000e+00 9.43179209e-01 3.22904561e-04]]
[[0.00000000e+00 1.00000000e+00 9.43599180e-01 3.18079156e-04]]
[[0.00000000e+00 1.00000000e+00 9.44016093e-01 3.13325861e-04]]
[[0.00000000e+00 1.00000000e+00 9.44429971e-01 3.08643597e-04]]
[[0.00000000e+00 1.00000000e+00 9.44840834e-01 3.04031305e-04]]
[[0.00000000e+00 1.00000000e+00 9.45248704e-01 2.99487937e-04]]
[[0.00000000e+00 1.00000000e+00 9.45653602e-01 2.95012464e-04]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 2.90603871e-04]]
[[0.0000000e+00 1.0000000e+00 1.0000000e+00 2.8626116e-04]]
[[0.00000000e+00 1.00000000e+00 9.46850673e-01 2.81983345e-04]]
[[0.00000000e+00 1.00000000e+00 9.47243892e-01 2.77769456e-04]]
[[0.00000000e+00 1.00000000e+00 9.47634242e-01 2.73618539e-04]]
[[0.00000000e+00 1.00000000e+00 9.48021744e-01 2.69529652e-04]]
[[0.00000000e+00 1.00000000e+00 9.48406418e-01 2.65501868e-04]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 2

[[0.00000000e+00 1.00000000e+00 9.97702671e-01 5.13328518e-07]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 5.05657465e-07]]
[[0.00000000e+00 1.00000000e+00 9.97736982e-01 4.98101046e-07]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 4.90657549e-07]]
[[0.00000000e+00 1.00000000e+00 9.97770781e-01 4.83325285e-07]]
[[0.00000000e+00 1.00000000e+00 9.97787491e-01 4.76102593e-07]]
[[0.00000000e+00 1.00000000e+00 9.97804076e-01 4.68987835e-07]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 4.61979398e-07]]
[[0.00000000e+00 1.00000000e+00 9.97836873e-01 4.55075693e-07]]
[[0.00000000e+00 1.00000000e+00 9.97853088e-01 4.48275156e-07]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 4.41576244e-07]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 4.34977439e-07]]
[[0.00000000e+00 1.00000000e+00 9.97901007e-01 4.28477245e-07]]
[[0.         1.         0.99791674 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.97932358e-01 4.15766817e-07]]
[[0.00000000e+00 1.00000000e+00 9.97947857e-01 4.0955370

[[0.00000000e+00 1.00000000e+00 9.99760006e-01 5.59632170e-09]]
[[0.00000000e+00 1.00000000e+00 9.99760906e-01 5.55442798e-09]]
[[0.00000000e+00 1.00000000e+00 9.99761802e-01 5.51284788e-09]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 5.47157905e-09]]
[[0.00000000e+00 1.00000000e+00 9.99763585e-01 5.43061915e-09]]
[[0.         1.         0.99976447 0.        ]]
[[0.         1.         0.99976536 0.        ]]
[[0.         1.         0.99976624 0.        ]]
[[0.         1.         0.99976711 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99767985e-01 5.23037335e-09]]
[[0.0000000e+00 1.0000000e+00 1.0000000e+00 5.1912191e-09]]
[[0.         1.         0.99976972 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99770585e-01 5.11378773e-09]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 5.07550624e-09]]
[[0.00000000e+00 1.00000000e+00 9.99772302e-01 5.03751132e-09]]
[[0.         1.         0.99977316 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99774007e-01 4.96237262e-09]]
[[0.00000000

[[0.00000000e+00 1.00000000e+00 9.99961632e-01 1.43020091e-10]]
[[0.00000000e+00 1.00000000e+00 9.99961776e-01 1.41949451e-10]]
[[0.00000000e+00 1.00000000e+00 9.99961919e-01 1.40886827e-10]]
[[0.00000000e+00 1.00000000e+00 9.99962062e-01 1.39832157e-10]]
[[0.00000000e+00 1.00000000e+00 9.99962204e-01 1.38785382e-10]]
[[0.00000000e+00 1.00000000e+00 9.99962346e-01 1.37746443e-10]]
[[0.00000000e+00 1.00000000e+00 9.99962487e-01 1.36715282e-10]]
[[0.00000000e+00 1.00000000e+00 9.99962628e-01 1.35691840e-10]]
[[0.00000000e+00 1.00000000e+00 9.99962768e-01 1.34676059e-10]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99963047e-01 1.32667253e-10]]
[[0.00000000e+00 1.00000000e+00 9.99963185e-01 1.31674115e-10]]
[[0.00000000e+00 1.00000000e+00 9.99963323e-01 1.30688410e-10]]
[[0.00000000e+00 1.00000000e+00 9.99963461e-01 1.29710085e-10]]
[[0.00000000e+00 1.00000000e+00 9.99963598e-01 1.28739084e-10]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 1.27775351e-10]]
[[0.00000000e+00 1.00000

[[0.         1.         0.99998706 0.        ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 1.62024116e-11]]
[[0.00000000e+00 1.00000000e+00 9.99987110e-01 1.61417095e-11]]
[[0.00000000e+00 1.00000000e+00 9.99987134e-01 1.60812349e-11]]
[[0.00000000e+00 1.00000000e+00 9.99987158e-01 1.60209868e-11]]
[[0.00000000e+00 1.00000000e+00 9.99987182e-01 1.59609644e-11]]
[[0.00000000e+00 1.00000000e+00 9.99987207e-01 1.59011669e-11]]
[[0.00000000e+00 1.00000000e+00 9.99987231e-01 1.58415934e-11]]
[[0.00000000e+00 1.00000000e+00 9.99987254e-01 1.57822431e-11]]
[[0.         1.         0.99998728 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99987302e-01 1.56642088e-11]]
[[0.         1.         0.99998733 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99987350e-01 1.55470572e-11]]
[[0.00000000e+00 1.00000000e+00 9.99987374e-01 1.54888104e-11]]
[[0.00000000e+00 1.00000000e+00 9.99987397e-01 1.54307819e-11]]
[[0.00000000e+00 1.00000000e+00 9.99987421e-01 1.53729707e-11]]
[[0.00000000e+00 1.00000

[[0.00000000e+00 1.00000000e+00 9.99994994e-01 2.43423486e-12]]
[[0.00000000e+00 1.00000000e+00 9.99995004e-01 2.42511504e-12]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99995023e-01 2.40697777e-12]]
[[0.00000000e+00 1.00000000e+00 9.99995032e-01 2.39796007e-12]]
[[0.         1.         0.99999504 0.        ]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99995060e-01 2.37110915e-12]]
[[0.00000000e+00 1.00000000e+00 9.99995069e-01 2.36222583e-12]]
[[0.00000000e+00 1.00000000e+00 9.99995078e-01 2.35337579e-12]]
[[0.00000000e+00 1.00000000e+00 9.99995087e-01 2.34455890e-12]]
[[0.00000000e+00 1.00000000e+00 9.99995097e-01 2.33577505e-12]]
[[0.0000000e+00 1.0000000e+00 1.0000000e+00 2.3270241e-12]]
[[0.00000000e+00 1.00000000e+00 9.99995115e-01 2.31830595e-12]]
[[0.00000000e+00 1.00000000e+00 9.99995124e-01 2.30962045e-12]]
[[0.00000000e+00 1.00000000e+00 9.99995133e-01 2.30096749e-12]]
[[0.00000000e+00 1.00000000e+00 9.99995142e-01 2.29234695e-12]]
[[0.00000000e+00 1.00000000e

[[0.00000000e+00 1.00000000e+00 1.00000000e+00 7.73545229e-13]]
[[0.00000000e+00 1.00000000e+00 9.99997181e-01 7.72095512e-13]]
[[0.00000000e+00 1.00000000e+00 9.99997184e-01 7.70648512e-13]]
[[0.         1.         0.99999719 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99997189e-01 7.67762641e-13]]
[[0.00000000e+00 1.00000000e+00 9.99997191e-01 7.66323761e-13]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99997197e-01 7.63454085e-13]]
[[0.00000000e+00 1.00000000e+00 9.99997199e-01 7.62023280e-13]]
[[0.00000000e+00 1.00000000e+00 9.99997202e-01 7.60595156e-13]]
[[0.00000000e+00 1.00000000e+00 9.99997205e-01 7.59169709e-13]]
[[0.00000000e+00 1.00000000e+00 9.99997207e-01 7.57746933e-13]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 7.56326823e-13]]
[[0.00000000e+00 1.00000000e+00 9.99997212e-01 7.54909375e-13]]
[[0.00000000e+00 1.00000000e+00 9.99997215e-01 7.53494584e-13]]
[[0.00000000e+00 1.00000000e+00 9.99997218e-01 7.52082444e-13]]
[[0.         1.         0.99999722 0.   

[[0.00000000e+00 1.00000000e+00 9.99998205e-01 3.13190066e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998206e-01 3.12603109e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998208e-01 3.12017253e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998210e-01 3.11432495e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998211e-01 3.10848833e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998213e-01 3.10266265e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998215e-01 3.09684788e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998216e-01 3.09104401e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998218e-01 3.08525102e-13]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99998221e-01 3.07369759e-13]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99998225e-01 3.06218742e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998226e-01 3.05644851e-13]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.05072036e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998230e-01 3.04500294e-13]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.03929624e-13]]
[[0.0000

[[0.00000000e+00 1.00000000e+00 9.99998692e-01 1.66296072e-13]]
[[0.         1.         0.99999869 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99998693e-01 1.65984486e-13]]
[[0.         1.         0.99999869 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99998694e-01 1.65673484e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998695e-01 1.65518202e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998695e-01 1.65363065e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998696e-01 1.65208073e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998697e-01 1.65053227e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998697e-01 1.64898526e-13]]
[[0.0000000e+00 1.0000000e+00 1.0000000e+00 1.6474397e-13]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 1.64589558e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998699e-01 1.64435292e-13]]
[[0.0000000e+00 1.0000000e+00 1.0000000e+00 1.6428117e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998700e-01 1.64127192e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998701e-01 1.63973359e-13]]
[[0.00000000e+00

[[0.00000000e+00 1.00000000e+00 1.00000000e+00 1.07223657e-13]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 1.07123158e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998950e-01 1.07022754e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998951e-01 1.06922443e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998951e-01 1.06822227e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998952e-01 1.06722105e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998952e-01 1.06622076e-13]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 1.06522141e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998953e-01 1.06422300e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998954e-01 1.06322553e-13]]
[[0.         1.         0.99999895 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99998955e-01 1.06123338e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998955e-01 1.06023871e-13]]
[[0.00000000e+00 1.00000000e+00 9.99998956e-01 1.05924497e-13]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99998957e-01 1.05726028e-13]]
[[0.00000000e+00 1.00000000e+00 9.999989

[[0.00000000e+00 1.00000000e+00 9.99999096e-01 7.94657789e-14]]
[[0.        1.        0.9999991 0.       ]]
[[0.00000000e+00 1.00000000e+00 9.99999096e-01 7.93913059e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 7.93169027e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999097e-01 7.92797273e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999097e-01 7.92425692e-14]]
[[0. 1. 1. 0.]]
[[0.        1.        0.9999991 0.       ]]
[[0.        1.        0.9999991 0.       ]]
[[0.00000000e+00 1.00000000e+00 9.99999098e-01 7.90941113e-14]]
[[0.        1.        0.9999991 0.       ]]
[[0.00000000e+00 1.00000000e+00 9.99999098e-01 7.90199866e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 7.89829503e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999099e-01 7.89459314e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999099e-01 7.89089298e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999099e-01 7.88719456e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 7.88349787e-14]]
[[0.00000000e+00 1.00000

[[0.00000000e+00 1.00000000e+00 1.00000000e+00 6.53550566e-14]]
[[0.0000000e+00 1.0000000e+00 9.9999918e-01 6.5324425e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999180e-01 6.52938078e-14]]
[[0.         1.         0.99999918 0.        ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 6.52326164e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999181e-01 6.52020422e-14]]
[[0.         1.         0.99999918 0.        ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 6.51409367e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999181e-01 6.51104055e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999182e-01 6.50798886e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999182e-01 6.50493859e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999182e-01 6.50188976e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999182e-01 6.49884236e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999182e-01 6.49579638e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999182e-01 6.49275183e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999183e-01 6.48970871e-14]]
[[0.00000000

[[0.         1.         0.99999926 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999256e-01 5.37626240e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999256e-01 5.37500241e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999256e-01 5.37374272e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999256e-01 5.37248332e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999256e-01 5.37122422e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999257e-01 5.36996541e-14]]
[[0.0000000e+00 1.0000000e+00 1.0000000e+00 5.3687069e-14]]
[[0.         1.         0.99999926 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999257e-01 5.36619076e-14]]
[[0.         1.         0.99999926 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999257e-01 5.36367580e-14]]
[[0.         1.         0.99999926 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999257e-01 5.36116202e-14]]
[[0.         1.         0.99999926 0.        ]]
[[0.         1.         0.99999926 0.        ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 5.35739356e-14]]
[[0.00000000

[[0.        1.        0.9999993 0.       ]]
[[0.00000000e+00 1.00000000e+00 9.99999297e-01 4.79630629e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 4.79518222e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999298e-01 4.79405841e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 4.79293487e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 4.79181159e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999298e-01 4.79068858e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999298e-01 4.78956583e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999298e-01 4.78844334e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999298e-01 4.78732111e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999298e-01 4.78619915e-14]]
[[0. 1. 1. 0.]]
[[0.        1.        0.9999993 0.       ]]
[[0.        1.        0.9999993 0.       ]]
[[0.00000000e+00 1.00000000e+00 9.99999298e-01 4.78171393e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999299e-01 4.78059328e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 4.77947289e-14]]
[[0.00000000e+00 1.0

[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999335e-01 4.29448654e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 4.29398329e-14]]
[[0.         1.         0.99999934 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999335e-01 4.29297698e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 4.29247391e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999335e-01 4.29197090e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999335e-01 4.29146795e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999335e-01 4.29096506e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999335e-01 4.29046222e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999335e-01 4.28995945e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999336e-01 4.28945673e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999336e-01 4.28895408e-14]]
[[0.         1.         0.99999934 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999336e-01 4.28794894e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999336e-01 4.28744646e-14]]
[[0.         1.         0.99999934 0.        ]]
[[0.0000

[[0.         1.         0.99999935 0.        ]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999355e-01 4.04201887e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999355e-01 4.04107160e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999355e-01 4.04059805e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999355e-01 4.04012456e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999355e-01 4.03965112e-14]]
[[0.         1.         0.99999936 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999355e-01 4.03870441e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999355e-01 4.03823114e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999355e-01 4.03775792e-14]]
[[0.         1.         0.99999936 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999355e-01 4.03681166e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 4.03633861e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999355e-01 4.03586561e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999356e-01 4.03539267e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 4.0349197

[[0.00000000e+00 1.00000000e+00 9.99999372e-01 3.83258553e-14]]
[[0.         1.         0.99999937 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999372e-01 3.83213641e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999372e-01 3.83191188e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999372e-01 3.83168736e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.83146285e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.83123835e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.83101387e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999372e-01 3.83078940e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999372e-01 3.83056494e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.83034049e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.83011606e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999372e-01 3.82989165e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999372e-01 3.82966724e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999372e-01 3.82944285e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.8292184

[[0.00000000e+00 1.00000000e+00 9.99999380e-01 3.73941773e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999380e-01 3.73919863e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999380e-01 3.73897954e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999380e-01 3.73876046e-14]]
[[0.         1.         0.99999938 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999380e-01 3.73832234e-14]]
[[0.0000000e+00 1.0000000e+00 9.9999938e-01 3.7381033e-14]]
[[0.         1.         0.99999938 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999380e-01 3.73766526e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.73744626e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999380e-01 3.73722727e-14]]
[[0.0000000e+00 1.0000000e+00 9.9999938e-01 3.7370083e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999380e-01 3.73678934e-14]]
[[0.         1.         0.99999938 0.        ]]
[[0.         1.         0.99999938 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999380e-01 3.73613253e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999380e-01 3

[[0.00000000e+00 1.00000000e+00 9.99999388e-01 3.63443233e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.63421938e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999388e-01 3.63400644e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999388e-01 3.63379352e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999388e-01 3.63358060e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999388e-01 3.63336770e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.63315481e-14]]
[[0.         1.         0.99999939 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999389e-01 3.63272907e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999389e-01 3.63251622e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999389e-01 3.63230338e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999389e-01 3.63209055e-14]]
[[0.         1.         0.99999939 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999389e-01 3.63166493e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999389e-01 3.63145214e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999389e-01 3.63123937e-14]]
[[0.0000

[[0.         1.         0.99999939 0.        ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.58158117e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999393e-01 3.58147624e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.58137131e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999393e-01 3.58126639e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999393e-01 3.58116147e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.58105655e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999393e-01 3.58095164e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.58084673e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.58074183e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999393e-01 3.58063692e-14]]
[[0.         1.         0.99999939 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999393e-01 3.58042712e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999393e-01 3.58032223e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999393e-01 3.58021734e-14]]
[[0.         1.         0.99999939 0.        ]]
[[0.00000000e+00 1.00000

[[0.00000000e+00 1.00000000e+00 9.99999397e-01 3.53664071e-14]]
[[0.0000000e+00 1.0000000e+00 1.0000000e+00 3.5365371e-14]]
[[0.        1.        0.9999994 0.       ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.53632988e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999397e-01 3.53622628e-14]]
[[0.        1.        0.9999994 0.       ]]
[[0.00000000e+00 1.00000000e+00 9.99999397e-01 3.53601908e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999397e-01 3.53591549e-14]]
[[0.0000000e+00 1.0000000e+00 1.0000000e+00 3.5358119e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999397e-01 3.53570831e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999397e-01 3.53560473e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999397e-01 3.53550114e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999397e-01 3.53539757e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999397e-01 3.53529399e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999397e-01 3.53519042e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999397e-01 3.53508685e-14]]
[[0.00000000e+00 1.00000

[[0.00000000e+00 1.00000000e+00 9.99999399e-01 3.50553892e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999399e-01 3.50548757e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999399e-01 3.50543622e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.50538487e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999399e-01 3.50533353e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999399e-01 3.50528218e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999399e-01 3.50523083e-14]]
[[0.        1.        0.9999994 0.       ]]
[[0.00000000e+00 1.00000000e+00 9.99999399e-01 3.50512814e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999399e-01 3.50507680e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999399e-01 3.50502545e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999399e-01 3.50497411e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999399e-01 3.50492277e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999399e-01 3.50487143e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.50476875e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999399e-

[[0.00000000e+00 1.00000000e+00 9.99999401e-01 3.48317027e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999401e-01 3.48311925e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999401e-01 3.48306823e-14]]
[[0.        1.        0.9999994 0.       ]]
[[0.00000000e+00 1.00000000e+00 9.99999401e-01 3.48296618e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999401e-01 3.48291516e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999401e-01 3.48286415e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999401e-01 3.48281313e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999401e-01 3.48276211e-14]]
[[0.        1.        0.9999994 0.       ]]
[[0.00000000e+00 1.00000000e+00 9.99999401e-01 3.48266008e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999401e-01 3.48260906e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.48250703e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999401e-01 3.48245602e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999401e-01 3.48240501e-14]]
[[0.000000e+00 1.000000e+00 1.000000e+00 3.482354e-14]]
[[0.0000

[[0.00000000e+00 1.00000000e+00 9.99999403e-01 3.46393681e-14]]
[[0.        1.        0.9999994 0.       ]]
[[0.00000000e+00 1.00000000e+00 9.99999403e-01 3.46388607e-14]]
[[0.        1.        0.9999994 0.       ]]
[[0.        1.        0.9999994 0.       ]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.46378459e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999403e-01 3.46375922e-14]]
[[0.        1.        0.9999994 0.       ]]
[[0.00000000e+00 1.00000000e+00 9.99999403e-01 3.46370849e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999403e-01 3.46368312e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999403e-01 3.46365775e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999403e-01 3.46363238e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999403e-01 3.46360701e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999403e-01 3.46355628e-14]]
[[0.        1.        0.9999994 0.       ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.46350554e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+

[[0.        1.        0.9999994 0.       ]]
[[0.        1.        0.9999994 0.       ]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999404e-01 3.45231123e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999404e-01 3.45228594e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999404e-01 3.45226066e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999404e-01 3.45223537e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999404e-01 3.45221009e-14]]
[[0.        1.        0.9999994 0.       ]]
[[0.00000000e+00 1.00000000e+00 9.99999404e-01 3.45215952e-14]]
[[0. 1. 1. 0.]]
[[0.        1.        0.9999994 0.       ]]
[[0.        1.        0.9999994 0.       ]]
[[0.00000000e+00 1.00000000e+00 9.99999404e-01 3.45205838e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999404e-01 3.45203310e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999404e-01 3.45200781e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999404e-01 3.45198253e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.45195725e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+

[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.44192190e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.44190929e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.44189669e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.44188408e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.44187148e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.44185887e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.44184627e-14]]
[[0.        1.        0.9999994 0.       ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.44182106e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.44180846e-14]]
[[0.        1.        0.9999994 0.       ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.44178325e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.44177064e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.44175804e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.44174544e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.44173283e-14]]
[[0.00000000e+00

[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.43651872e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.43650614e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.43649355e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.43648097e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.43646838e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.43644322e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.43641805e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.43640546e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.43639288e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.43638029e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.43636771e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.43634254e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.43631737e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999405e-01 3.43630479e-14]]
[[0.0000

[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.43138163e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.43137535e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.43136278e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.43135650e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.43135021e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.43134393e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.43133765e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.43132508e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.43131252e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.43130623e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.43129995e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.43129367e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.43128738e-14]]
[[0.         1.         

[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42848636e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42848009e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42847381e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42846753e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42846125e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42845498e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42844870e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42843614e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42842986e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42842359e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42841731e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42840475e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42839848e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42839220e-14]]
[[0.         1.         0.99999941 0.   

[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42551200e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42550573e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42549319e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42548691e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42547437e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42546810e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42546182e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42545555e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42544928e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42544301e-14]]
prediction on the training set
[0 0 0 0]
% inaccuracy
50.0
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42543674e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42543046e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42542733e-14]]
[[0.00000000e

[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42411043e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42410729e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42410102e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42409476e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42409162e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42408849e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42408222e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42407908e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42407595e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42407281e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42406968e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42406654e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42406341e-14]]
[[0.0000

[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42263736e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42263423e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42263109e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42262796e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42262482e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42262169e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42261856e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42261542e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42261229e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42260916e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42260602e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42260289e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999406e-01 3.42259976e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42259662e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42259349e-14]]
[[0.00000000e+00 1.00000000e+00 9.999994

[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42178671e-14]]
[[0. 1. 1. 0.]]
[[0. 1. 1. 0.]]
[[0.         1.         0.99999941 0.        ]]
[[0. 1. 1. 0.]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42177732e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42177575e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42177418e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42177262e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42176948e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42176792e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42176479e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42176165e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42176009e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000

[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42107879e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42107722e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42107566e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42107409e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42107252e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42106939e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42106783e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42106469e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42106313e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42106156e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42106000e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42105843e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42105686e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.4210537

[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42053072e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42052993e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42052915e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42052837e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42052758e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42052680e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42052602e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42052524e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42052445e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42052289e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42052210e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42052132e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42051976e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42051897e-14]]
[[0.00000000e+00 1.00000000e+00 9.999994

[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42013381e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42013303e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42013146e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42013068e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42012990e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.42012833e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42012755e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42012676e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42012598e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42012520e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42012442e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42012363e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.42012207e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000

[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41990446e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41990406e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41990367e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41990328e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41990289e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41990250e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41990211e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41990172e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.41990132e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41990093e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41990054e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.41990015e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41989976e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.41989937e-14]]
[[0. 1. 1. 0.]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.999994

[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41975143e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41975104e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41975065e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41975026e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41974987e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41974908e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41974869e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41974791e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41974752e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41974713e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41974673e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41974634e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41974595e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41974556e-14]]
[[0.0000

[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41958080e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.41958041e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41958002e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41957963e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41957924e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41957885e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41957845e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41957806e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.41957767e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41957728e-14]]
[[0. 1. 1. 0.]]
[[0. 1. 1. 0.]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.41957571e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41957493e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41957454e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41957415e-14]]
[[0.    

[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41946751e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41946732e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41946712e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41946692e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.41946673e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41946653e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41946634e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41946595e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41946575e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.41946555e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41946536e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41946516e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41946497e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41946477e-14]]
[[0.0000

[[0.         1.         0.99999941 0.        ]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41937594e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41937575e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41937555e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.41937516e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.41937496e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41937438e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41937418e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41937399e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41937379e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41937359e-14]]
[[0.0000000e+00 1.0000000e+00 1.0000000e+00 3.4193734e-14]]
[[0.0000000e+00 1.0000000e+00 1.0000000e+00 3.4193732e-14]]


[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41932468e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41932458e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41932448e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41932439e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41932429e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41932419e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41932409e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41932399e-14]]
[[0.0000000e+00 1.0000000e+00 1.0000000e+00 3.4193239e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41932370e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.41932351e-14]]
[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41932331e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41932321e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41932311e-14]]
[[0.00000000e+00 1.00000000e

[[0. 1. 1. 0.]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41928203e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41928183e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41928173e-14]]
[[0.00000000e+00 1.00000000e+00 1.00000000e+00 3.41928164e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41928154e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41928144e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41928134e-14]]
[[0.         1.         0.99999941 0.        ]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41928115e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41928105e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41928095e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41928085e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41928076e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.41928066e-14]]
[[0.00000000e+00 1.00000000e+00 9.99999407e-01 3.4192805

In [39]:
NN.cost

[array([0.00000000e+00, 5.00000000e-01, 1.05004013e-04, 1.99975404e-01]),
 array([0.        , 0.5       , 0.5       , 0.19698702]),
 array([0.00000000e+00, 5.00000000e-01, 2.23550427e-07, 1.94043297e-01]),
 array([0.        , 0.5       , 0.5       , 0.19114356]),
 array([0.00000000e+00, 5.00000000e-01, 1.21717658e-04, 1.88287160e-01]),
 array([0.        , 0.5       , 0.5       , 0.18547344]),
 array([0.00000000e+00, 5.00000000e-01, 4.59439142e-04, 1.82701775e-01]),
 array([0.        , 0.5       , 0.00070634, 0.17997153]),
 array([0.        , 0.5       , 0.00100369, 0.17728208]),
 array([0.        , 0.5       , 0.00135032, 0.17463282]),
 array([0.        , 0.5       , 0.0017451 , 0.17202315]),
 array([0.        , 0.5       , 0.00218691, 0.16945248]),
 array([0.        , 0.5       , 0.00267465, 0.16692022]),
 array([0.        , 0.5       , 0.00320723, 0.16442581]),
 array([0.       , 0.5      , 0.0037836, 0.       ]),
 array([0.        , 0.5       , 0.00440271, 0.        ]),
 array([0.  

In [24]:
y_predicted = NN.predict(X_test)
print(y_predicted)
#save_predictions('ans1-uni', y_predicted)

NameError: name 'X_test' is not defined

In [ ]:
# test if your numpy file has been saved correctly
loaded_y = np.load('ans1-uni.npy')
print(loaded_y.shape)
loaded_y[:10]

## Part 2: Regularizing the neural network
#### Add dropout and L2 regularization

In [29]:
sum(np.array([1,2,3]))

6

In [ ]:
y_predicted2 = NN2.predict(X)
save_predictions(y_predicted, 'ans2-uni')


    def train(self, X, y, iters=1000, alpha=0.001, batch_size=100, print_every=100):
        
        
        for i in range(0, iters):
            X_batch= X
            y_batch=y
            
            # forward prop
            AL, cache = self.forwardPropagation(X_batch)
            
            # compute loss
            cost, dAL = self.costFunction(AL, y_batch)

            # compute gradients
            gradients = self.backPropagation(dAL, AL, cache)

            # update weights and biases based on gradient
            self.updateParameters(gradients, alpha)
    
            if i % print_every == 0:
                
                if i % 500 == 0 and i != 0:
                    alpha /= 2


                print("prediction on the training set" )
                v_pred = self.predict(X_batch)
                print(v_pred)
                for i in range(len(v_pred)):
                    if v_pred[i]>=0.5:
                        v_pred[i]=1
                    else:
                        v_pred[i]=0
                print("% inaccuracy")
                c=0  
                for i in range(len(v_pred)):
                    if v_pred[i]!=y_batch[i]:
                        c= c+1
                        print(c)
                print(c/len(v_pred)*100)